/**
 * python-backend — Electron-side boot_core process manager.
 *
 * Architecture boundary (per architecture decision):
 *   啟動入口 (Electron main) 僅啟動頁面；後續交由啟動核心 (boot_core)
 *   去啟動主宰 (system sovereign)。
 *
 * This module ONLY spawns and stops the boot_core process.  It does NOT:
 *   - generate governance bootstrap tokens (boot_core does this)
 *   - probe backend HTTP health (boot_core supervises this)
 *   - perform auto-recovery or source repair (boot_core handles restarts)
 *
 * The Electron UI queries backend status via IPC commands to the backend
 * itself; this module only tracks whether boot_core is alive.
 *
 * Governance bootstrap material is created by createMainSystemGovernanceBootstrap
 * (from governance-bootstrap.ts) and preloaded by the launcher before the
 * backend starts.  boot_core independently generates its own fresh token per
 * spawn, so the Electron-side bootstrap is a preload attestation only.
 */
import { ChildProcess, spawn } from 'child_process'
import fs from 'node:fs'
import { app } from 'electron'
import {
  getBackendSessionToken,
  getIpcStateRoot,
  getWorkspaceInstanceId,
} from './ipcSession'
import { createMainSystemGovernanceBootstrap } from './governance-bootstrap'
import { getRuntimePathLibrary } from './pathLibrary'
import { getRuntimeEnvMap } from './runtime-env'
import { PRODUCT_VERSION } from './product-version'

let pythonProcess: ChildProcess | null = null
type BackendStatus = 'idle' | 'starting' | 'running' | 'stopping' | 'error'

let backendStatus: BackendStatus = 'idle'
let backendStartedAt: number | null = null
let backendReadyAt: number | null = null
let backendMessage = 'backend idle'
let backendLastError = ''

export function getBackendStatus(): BackendStatus {
  return backendStatus
}

export function getBackendRuntimeInfo() {
  return {
    status: backendStatus,
    ready: backendStatus === 'running',
    startedAt: backendStartedAt,
    readyAt: backendReadyAt,
    startupMs:
      backendStartedAt && backendReadyAt ? backendReadyAt - backendStartedAt : null,
    message: backendMessage,
    lastError: backendLastError,
  }
}

function spawnBootCore(
  paths: ReturnType<typeof getRuntimePathLibrary>,
  autoKillBackendPort = false
): void {
  backendMessage = 'spawning boot_core (startup core)'
  backendLastError = ''
  console.log('[Python Backend Manager] Spawning boot_core...')

  // Entry responsibility boundary: the launcher wakes the screen and spawns
  // the startup core (boot_core); boot_core awakens and supervises the system
  // backend (main.py).  Governance bootstrap token is generated by boot_core,
  // NOT by Electron.
  const backendArgs = ['-u', paths.bootCoreEntry, '--serve']
  if (autoKillBackendPort) backendArgs.push('--auto-kill-backend-port')

  const runtimeEnvironment = getRuntimeEnvMap()
  // Preload governance bootstrap material so the launcher attests to the
  // governance authority before boot_core spawns.  boot_core independently
  // generates its own fresh token per spawn; this preload is an attestation
  // that the launcher has verified the governance source integrity.
  try {
    const workspaceRoot = paths.workspaceRoot
    createMainSystemGovernanceBootstrap(workspaceRoot)
  } catch {
    // Best-effort preload; boot_core will generate its own token anyway.
  }
  pythonProcess = spawn(
    paths.pythonExecutable,
    backendArgs,
    {
      cwd: paths.workspaceRoot,
      env: {
        ...runtimeEnvironment,
        GPTBRIDGE_PROJECT_ROOT: paths.workspaceRoot,
        GPTBRIDGE_APP_VERSION: PRODUCT_VERSION,
        GPTBRIDGE_IPC_STATE_ROOT: getIpcStateRoot(),
        GPTBRIDGE_IPC_SESSION_TOKEN: getBackendSessionToken(),
      },
      stdio: ['ignore', 'pipe', 'pipe'],
      windowsHide: true,
    }
  )

  pythonProcess.stdout?.on('data', (data) => {
    const text = data.toString().trim()
    console.log(`[boot_core STDOUT]: ${text}`)
  })

  pythonProcess.stderr?.on('data', (data) => {
    const text = data.toString().trim()
    backendLastError = `${backendLastError}\n${text}`.trim().slice(-4_000)
    console.error(`[boot_core STDERR]: ${text}`)
  })

  pythonProcess.on('exit', (code, signal) => {
    console.log(
      `[Python Backend Manager] boot_core exited with code ${code} and signal ${signal}`
    )
    pythonProcess = null

    if (signal === 'SIGTERM' || code === 0) {
      backendStatus = 'idle'
      backendMessage = 'backend stopped'
      return
    }

    backendStatus = 'error'
    backendMessage = `boot_core exited unexpectedly (code ${code})`
  })

  pythonProcess.on('error', (err) => {
    console.error('[Python Backend Manager] Failed to spawn boot_core:', err)
    pythonProcess = null
    backendStatus = 'error'
    backendMessage = `boot_core spawn failed: ${err.message}`
  })

  // boot_core is now responsible for starting and supervising main.py.
  // Electron considers the backend "running" once boot_core is alive;
  // detailed health status is available via IPC to the backend itself.
  backendStatus = 'running'
  backendReadyAt = Date.now()
  backendMessage = 'boot_core supervising backend'
}

export function startBackend() {
  if (backendStatus === 'running') {
    console.warn('[Python Backend Manager] boot_core already running.')
    return
  }

  if (pythonProcess) {
    console.warn('[Python Backend Manager] boot_core process already exists.')
    return
  }

  const paths = getRuntimePathLibrary()

  if (!fs.existsSync(paths.pythonExecutable)) {
    backendStatus = 'error'
    backendMessage = `Python executable not found: ${paths.pythonExecutable}`
    console.error(
      `[Python Backend Manager] Python executable not found: ${paths.pythonExecutable}`
    )
    return
  }

  if (!fs.existsSync(paths.bootCoreEntry)) {
    backendStatus = 'error'
    backendMessage = `boot_core entry not found: ${paths.bootCoreEntry}`
    console.error(
      `[Python Backend Manager] boot_core entry not found: ${paths.bootCoreEntry}`
    )
    return
  }

  backendStatus = 'starting'
  backendStartedAt = Date.now()
  backendReadyAt = null
  backendMessage = 'spawning boot_core'
  spawnBootCore(paths)
}

export function ensureBackendStarted(): BackendStatus {
  if (backendStatus === 'error') {
    backendStatus = 'idle'
  }
  if (!pythonProcess && backendStatus !== 'running' && backendStatus !== 'starting') {
    startBackend()
  }
  return backendStatus
}

export async function stopBackend() {
  if (!pythonProcess) {
    if (backendStatus === 'starting') {
      backendStatus = 'idle'
      backendMessage = 'backend start cancelled'
    }
    return
  }

  backendStatus = 'stopping'
  backendMessage = 'stopping boot_core'
  console.log('[Python Backend Manager] Stopping boot_core...')
  const processToStop = pythonProcess
  const processId = processToStop.pid
  const exitedGracefully = await new Promise<boolean>((resolve) => {
    if (processToStop.exitCode !== null || processToStop.signalCode !== null) {
      resolve(true)
      return
    }
    let settled = false
    const finish = (value: boolean) => {
      if (settled) return
      settled = true
      clearTimeout(timer)
      resolve(value)
    }
    processToStop.once('exit', () => finish(true))
    const timer = setTimeout(() => finish(false), 1_500)
  })

  if (!exitedGracefully) {
    if (process.platform === 'win32' && processId) {
      await new Promise<void>((resolve) => {
        const terminator = spawn(
          'taskkill.exe',
          ['/PID', String(processId), '/T', '/F'],
          { windowsHide: true, stdio: 'ignore' }
        )
        terminator.once('exit', () => resolve())
        terminator.once('error', () => resolve())
      })
    } else {
      processToStop.kill('SIGTERM')
    }
  }

  if (pythonProcess === processToStop) pythonProcess = null
  backendStatus = 'idle'
  backendMessage = exitedGracefully
    ? 'backend stopped gracefully'
    : 'boot_core process tree stopped after graceful timeout'
}

export async function restartBackend() {
  if (pythonProcess) {
    await stopBackend()
  }
  startBackend()
  return backendStatus
}
