"""SQLite-flavoured statement translation for ``pg_adapter``.

Extracted from ``pg_adapter`` (source-size contract): owns the regex
rewrite pipeline (``translate``), the ``ON CONFLICT`` clause inference
(``_append_conflict_clause``) and the ``executescript`` statement
splitter (``_split_script``).
"""
from __future__ import annotations

import re
import threading
from collections import OrderedDict
from typing import Any, Iterator

_PRAGMA_RE = re.compile(r"^\s*PRAGMA\b", re.IGNORECASE)
_PRAGMA_TABLE_INFO_RE = re.compile(
    r"^\s*PRAGMA\s+table_info\s*\(\s*['\"]?([A-Za-z_][\w$]*)['\"]?\s*\)\s*;?\s*$",
    re.IGNORECASE,
)
_SQLITE_MASTER_RE = re.compile(
    r"SELECT\s+name\s+FROM\s+sqlite_master\s+WHERE\s+type\s*=\s*'table'"
    r"(?:\s+AND\s+name\s*=\s*'([^']*)')?",
    re.IGNORECASE,
)
_BEGIN_RE = re.compile(r"^\s*BEGIN\s+(IMMEDIATE|DEFERRED|EXCLUSIVE)\s*;?\s*$", re.IGNORECASE)
_INSERT_OR_RE = re.compile(r"^\s*INSERT\s+OR\s+(REPLACE|IGNORE)\s+INTO\b", re.IGNORECASE)
_REPLACE_INTO_RE = re.compile(r"^\s*REPLACE\s+INTO\b", re.IGNORECASE)
_DATETIME_NOW_RE = re.compile(r"datetime\s*\(\s*'now'\s*\)", re.IGNORECASE)
_STRFTIME_NOW_RE = re.compile(
    r"strftime\s*\(\s*'%(.*?)'\s*,\s*'now'\s*\)", re.IGNORECASE
)
_INTEGER_PK_RE = re.compile(
    r"INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT", re.IGNORECASE
)

# Statement translation runs ~15 regex passes per query; the same
# statement texts recur constantly in the governed repositories, so cache
# translations that are pk_resolver-independent (only the INSERT OR
# REPLACE / REPLACE INTO conflict-clause path consults the resolver).
_translate_lock = threading.Lock()
_translate_cache: "OrderedDict[str, str]" = OrderedDict()
_TRANSLATE_CACHE_MAX = 1024


def _translate_meta(stmt: str) -> str | None:
    """Early-return forms: PRAGMA table_info, other PRAGMA, BEGIN modes."""
    pragma_info = _PRAGMA_TABLE_INFO_RE.match(stmt)
    if pragma_info:
        table = pragma_info.group(1).replace('"', '""')
        return (
            "SELECT ordinal_position - 1 AS cid, column_name AS name, "
            "data_type AS type, "
            "CASE WHEN is_nullable = 'NO' THEN 1 ELSE 0 END AS \"notnull\", "
            "column_default AS dflt_value, 0 AS pk "
            "FROM information_schema.columns "
            f"WHERE table_schema = current_schema() AND table_name = '{table}' "  # sql-ok: identifier validated by _PRAGMA_TABLE_INFO_RE charset
            "ORDER BY ordinal_position"
        )
    if _PRAGMA_RE.match(stmt):
        return ""
    if _BEGIN_RE.match(stmt):
        return "BEGIN"
    return None


def _rewrite_sqlite_exprs(stmt: str) -> str:
    """Expression-level sqlite -> PostgreSQL rewrites (schema/functions)."""
    stmt = _SQLITE_MASTER_RE.sub(
        lambda m: (
            "SELECT table_name AS name FROM information_schema.tables "
            "WHERE table_type='BASE TABLE' AND table_schema = current_schema()"
            + (
                f" AND table_name='{m.group(1)}'"
                if m.group(1) is not None
                else ""
            )
        ),
        stmt,
    )
    stmt = _DATETIME_NOW_RE.sub("now()", stmt)
    # COLLATE NOCASE: sqlite's case-insensitive collation has no direct
    # PG builtin — drop it inside CREATE TABLE (case-sensitive key, as in
    # the migrated schemas) and lower() the operand in query expressions.
    if re.match(r"\s*CREATE\s+TABLE", stmt, re.IGNORECASE):
        stmt = re.sub(r"\s+COLLATE\s+NOCASE", "", stmt, flags=re.IGNORECASE)
    else:
        stmt = re.sub(
            r"([A-Za-z_][\w.]*)\s+COLLATE\s+NOCASE",
            r"lower(\1)",
            stmt,
            flags=re.IGNORECASE,
        )
    # sqlite LIKE is ASCII case-insensitive; ILIKE is the faithful match.
    stmt = re.sub(
        r"\bLIKE\b(?=\s+(?:\?|'|\())", "ILIKE", stmt, flags=re.IGNORECASE
    )
    # sqlite idiom: LIMIT -1 means "no bound" (usually with OFFSET).
    stmt = re.sub(r"\bLIMIT\s+-1\b", "LIMIT ALL", stmt, flags=re.IGNORECASE)
    # strftime('%Y-%m-%dT%H:%M:%SZ','now') keeps its ISO-8601 text shape;
    # any other format degrades to now() (timestamp).
    stmt = _STRFTIME_NOW_RE.sub(
        lambda m: (
            "to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD\"T\"HH24:MI:SS\"Z\"')"
            if m.group(1) == "Y-%m-%dT%H:%M:%SZ"
            else "now()"
        ),
        stmt,
    )
    # julianday(x) -> extract(epoch from x)/86400 + 2440587.5 (single-arg
    # form only; callers needing strftime-style args translate explicitly).
    stmt = re.sub(
        r"julianday\s*\(\s*([^()]+?)\s*\)",
        r"extract(epoch from \1)/86400.0 + 2440587.5",
        stmt,
        flags=re.IGNORECASE,
    )
    return _INTEGER_PK_RE.sub(
        "bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", stmt
    )


def translate(statement: str, pk_resolver: Any = None) -> str:
    """Translate a sqlite-flavoured statement into PostgreSQL syntax.

    ``PRAGMA`` returns an empty string (caller treats as no-op).
    ``?`` placeholders become ``%s`` (psycopg).  Literal ``%`` that is
    not part of a psycopg placeholder is escaped first.

    *pk_resolver* (optional) maps a table name to its primary-key column
    list; used to build the correct ``ON CONFLICT`` target for
    ``INSERT OR REPLACE`` on composite keys.
    """
    with _translate_lock:
        cached = _translate_cache.get(statement)
        if cached is not None:
            _translate_cache.move_to_end(statement)
            return cached
    stmt = statement.strip()
    meta = _translate_meta(stmt)
    if meta is not None:
        return meta
    stmt = _rewrite_sqlite_exprs(stmt)
    # INSERT OR REPLACE/IGNORE + REPLACE INTO -> ON CONFLICT form.
    m = _INSERT_OR_RE.match(stmt)
    mode = None
    if m:
        mode = m.group(1).upper()
        stmt = re.sub(r"^\s*INSERT\s+OR\s+(REPLACE|IGNORE)\s+INTO", "INSERT INTO", stmt, flags=re.IGNORECASE)
    elif _REPLACE_INTO_RE.match(stmt):
        mode = "REPLACE"
        stmt = re.sub(r"^\s*REPLACE\s+INTO", "INSERT INTO", stmt, flags=re.IGNORECASE)
    if mode:
        stmt = _append_conflict_clause(stmt, mode, pk_resolver)
    # placeholder translation: escape stray % then ? -> %s
    stmt = re.sub(r"%(?![sbt])", "%%", stmt).replace("?", "%s")
    if mode is None:
        with _translate_lock:
            _translate_cache[statement] = stmt
            _translate_cache.move_to_end(statement)
            while len(_translate_cache) > _TRANSLATE_CACHE_MAX:
                _translate_cache.popitem(last=False)
    return stmt


def _append_conflict_clause(stmt: str, mode: str, pk_resolver: Any = None) -> str:
    """Append an ON CONFLICT clause inferred from the column list."""
    m = re.match(
        r"INSERT\s+INTO\s+([^\s(]+)\s*\(([^)]*)\)\s*VALUES\s*\(",
        stmt,
        re.IGNORECASE,
    )
    if not m:
        # INSERT INTO t SELECT ... / DEFAULT VALUES — degrade to DO NOTHING
        return stmt + " ON CONFLICT DO NOTHING" if mode == "IGNORE" else stmt
    table, columns = m.group(1), [c.strip() for c in m.group(2).split(",")]
    if mode == "IGNORE":
        return stmt + " ON CONFLICT DO NOTHING"
    if len(columns) < 2:
        return stmt + " ON CONFLICT DO NOTHING"
    # REPLACE / OR REPLACE: upsert on the table's real primary key.
    # Composite keys are resolved through the connection's PK map; when no
    # resolver is available the first column is the governed-store
    # convention for single-column primary keys.
    bare = table.strip('"').split(".")[-1]
    pk_cols = pk_resolver(bare) if pk_resolver is not None else None
    if pk_cols is None:
        pk_cols = [columns[0]]
    updates = ", ".join(
        f"{c} = EXCLUDED.{c}" for c in columns if c not in pk_cols
    )
    target = ", ".join(pk_cols)
    if not updates:
        return stmt + f" ON CONFLICT ({target}) DO NOTHING"
    return stmt + f" ON CONFLICT ({target}) DO UPDATE SET {updates}"  # sql-ok: identifiers derive from parsed INSERT column list / PK metadata, values parameterized


def _resolve_pk_cached(
    cache: dict[str, list[str] | None], connection: Any, table: str
) -> list[str] | None:
    """Return the primary-key column list for *table* in search_path.

    Cached per connection; ``None`` (cached) means the table has no
    primary key — callers then fall back to the first INSERT column.
    """
    if table in cache:
        return cache[table]
    row_cur = connection.cursor()
    row_cur.execute(
        "SELECT kcu.column_name FROM information_schema.table_constraints tc "
        "JOIN information_schema.key_column_usage kcu "
        "ON tc.constraint_schema = kcu.constraint_schema "
        "AND tc.constraint_name = kcu.constraint_name "
        "WHERE tc.constraint_type = 'PRIMARY KEY' "
        "AND tc.table_schema = current_schema() AND tc.table_name = %s "
        "ORDER BY kcu.ordinal_position",
        (table,),
    )
    cols = [str(r[0]) for r in row_cur.fetchall()]
    row_cur.close()
    cache[table] = cols or None
    return cache[table]


def _split_inside(state: dict[str, bool], current: list[str], ch: str, nxt: str) -> int:
    """Consume one char inside a quoted/comment region; 0 = normal state."""
    if state["line_comment"]:
        current.append(ch)
        if ch == "\n":
            state["line_comment"] = False
        return 1
    if state["block_comment"]:
        current.append(ch)
        if nxt == "*/":
            current.append("/")
            state["block_comment"] = False
            return 2
        return 1
    if state["dollar"]:
        current.append(ch)
        if nxt == "$$":
            current.append("$")
            state["dollar"] = False
            return 2
        return 1
    if state["string"]:
        current.append(ch)
        if ch == "'":
            state["string"] = False
        return 1
    return 0


def _split_normal(state: dict[str, bool], current: list[str], ch: str, nxt: str) -> int | str:
    """Consume one char in normal state; returns ``";"`` on a boundary."""
    if nxt == "--":
        state["line_comment"] = True
        current.append(ch)
        return 1
    if nxt == "/*":
        state["block_comment"] = True
        current.append(ch)
        return 1
    if nxt == "$$":
        state["dollar"] = True
        current.append(ch)
        current.append("$")
        return 2
    if ch == "'":
        state["string"] = True
        current.append(ch)
        return 1
    if ch == ";":
        return ";"
    current.append(ch)
    return 1


def _split_script(script: str) -> Iterator[str]:
    """Split a multi-statement script on ``;`` while respecting ``$$``-quoted
    function bodies (PL/pgSQL), single-quoted strings, ``--`` line comments
    and ``/* */`` block comments."""
    parts: list[str] = []
    current: list[str] = []
    state = {"dollar": False, "string": False, "line_comment": False, "block_comment": False}
    i = 0
    while i < len(script):
        ch = script[i]
        nxt = script[i : i + 2]
        step = _split_inside(state, current, ch, nxt)
        if step == 0:
            step = _split_normal(state, current, ch, nxt)
            if step == ";":
                statement = "".join(current).strip()
                if statement:
                    parts.append(statement)
                current = []
                step = 1
        i += step
    tail = "".join(current).strip()
    if tail:
        parts.append(tail)
    return iter(parts)
