"""pg_adapter — PostgreSQL-backed drop-in for ``sqlite3`` call sites.

A8/A503/A610/A621: PostgreSQL is the sole structured-data authority;
SQLite is retired.  This module gives legacy ``sqlite3.connect(...)``
call sites a minimal migration surface so each store can move to
PostgreSQL without rewriting its query layer:

    # before
    connection = sqlite3.connect(path, isolation_level=None)
    connection.row_factory = sqlite3.Row
    # after
    connection = pg_adapter.connect(schema="gptbridge_mod_xingcheng")

Supported surface (what the governed stores actually use):

* ``connect(...)`` -> :class:`PgConnection` with ``execute``,
  ``executemany``, ``executescript``, ``commit``, ``rollback``,
  ``close``, context-manager protocol and ``row_factory``-style dict
  rows (``cursor.description`` named access).
* Statement translation: ``?`` -> ``%s``, ``INSERT OR REPLACE`` ->
  ``INSERT ... ON CONFLICT DO UPDATE`` (column list preserved, conflict
  target = the table's primary key), ``INSERT OR IGNORE`` ->
  ``ON CONFLICT DO NOTHING``, ``REPLACE INTO`` -> upsert,
  ``BEGIN IMMEDIATE``/``BEGIN DEFERRED`` -> ``BEGIN``,
  ``sqlite_master`` -> ``information_schema``, ``PRAGMA`` -> no-op
  (``journal_mode``/``synchronous``/``foreign_keys`` etc. — PG
  equivalents are server-side or already enforced), ``datetime('now')``
  -> ``now()``, ``AUTOINCREMENT``/``INTEGER PRIMARY KEY`` ->
  ``GENERATED BY DEFAULT AS IDENTITY``.
* Fail-closed: no DSN -> :class:`PgUnavailable` (never a silent local
  file fallback — that was the sqlite anti-pattern this removes).

NOT a general SQL transpiler — it covers the governed store surface;
callers that exercise exotic sqlite-isms must translate explicitly.
"""

from __future__ import annotations

import logging
import re
from typing import Any, Iterable, Iterator, Sequence

_logger = logging.getLogger("gptbridge.pg_adapter")


class PgUnavailable(RuntimeError):
    """Raised when no governed PostgreSQL DSN is resolvable."""


# ---------------------------------------------------------------------------
# Statement translation
# ---------------------------------------------------------------------------

_PRAGMA_RE = re.compile(r"^\s*PRAGMA\b", re.IGNORECASE)
_PRAGMA_TABLE_INFO_RE = re.compile(
    r"^\s*PRAGMA\s+table_info\s*\(\s*['\"]?([A-Za-z_][\w$]*)['\"]?\s*\)\s*;?\s*$",
    re.IGNORECASE,
)
_SQLITE_MASTER_RE = re.compile(
    r"SELECT\s+name\s+FROM\s+sqlite_master\s+WHERE\s+type\s*=\s*'table'",
    re.IGNORECASE,
)
_BEGIN_RE = re.compile(r"^\s*BEGIN\s+(IMMEDIATE|DEFERRED|EXCLUSIVE)\s*;?\s*$", re.IGNORECASE)
_INSERT_OR_RE = re.compile(r"^\s*INSERT\s+OR\s+(REPLACE|IGNORE)\s+INTO\b", re.IGNORECASE)
_REPLACE_INTO_RE = re.compile(r"^\s*REPLACE\s+INTO\b", re.IGNORECASE)
_DATETIME_NOW_RE = re.compile(r"datetime\s*\(\s*'now'\s*\)", re.IGNORECASE)
_STRFTIME_NOW_RE = re.compile(
    r"strftime\s*\(\s*'%(.*?)'\s*,\s*'now'\s*\)", re.IGNORECASE
)
_INTEGER_PK_RE = re.compile(
    r"INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT", re.IGNORECASE
)


def translate(statement: str) -> str:
    """Translate a sqlite-flavoured statement into PostgreSQL syntax.

    ``PRAGMA`` returns an empty string (caller treats as no-op).
    ``?`` placeholders become ``%s`` (psycopg).  Literal ``%`` that is
    not part of a psycopg placeholder is escaped first.
    """
    stmt = statement.strip()
    pragma_info = _PRAGMA_TABLE_INFO_RE.match(stmt)
    if pragma_info:
        table = pragma_info.group(1).replace('"', '""')
        return (
            "SELECT ordinal_position - 1 AS cid, column_name AS name, "
            "data_type AS type, "
            "CASE WHEN is_nullable = 'NO' THEN 1 ELSE 0 END AS \"notnull\", "
            "column_default AS dflt_value, 0 AS pk "
            "FROM information_schema.columns "
            f"WHERE table_schema = current_schema() AND table_name = '{table}' "  # sql-ok: identifier validated by _PRAGMA_TABLE_INFO_RE charset
            "ORDER BY ordinal_position"
        )
    if _PRAGMA_RE.match(stmt):
        return ""
    if _BEGIN_RE.match(stmt):
        return "BEGIN"
    stmt = _SQLITE_MASTER_RE.sub(
        "SELECT table_name AS name FROM information_schema.tables "
        "WHERE table_type='BASE TABLE'",
        stmt,
    )
    stmt = _DATETIME_NOW_RE.sub("now()", stmt)
    # strftime('%Y-%m-%dT%H:%M:%SZ','now') keeps its ISO-8601 text shape;
    # any other format degrades to now() (timestamp).
    stmt = _STRFTIME_NOW_RE.sub(
        lambda m: (
            "to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD\"T\"HH24:MI:SS\"Z\"')"
            if m.group(1) == "Y-%m-%dT%H:%M:%SZ"
            else "now()"
        ),
        stmt,
    )
    # julianday(x) -> extract(epoch from x)/86400 + 2440587.5 (single-arg
    # form only; callers needing strftime-style args translate explicitly).
    stmt = re.sub(
        r"julianday\s*\(\s*([^()]+?)\s*\)",
        r"extract(epoch from \1)/86400.0 + 2440587.5",
        stmt,
        flags=re.IGNORECASE,
    )
    stmt = _INTEGER_PK_RE.sub(
        "bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", stmt
    )
    # INSERT OR REPLACE/IGNORE + REPLACE INTO -> ON CONFLICT form.
    m = _INSERT_OR_RE.match(stmt)
    mode = None
    if m:
        mode = m.group(1).upper()
        stmt = re.sub(r"^\s*INSERT\s+OR\s+(REPLACE|IGNORE)\s+INTO", "INSERT INTO", stmt, flags=re.IGNORECASE)
    elif _REPLACE_INTO_RE.match(stmt):
        mode = "REPLACE"
        stmt = re.sub(r"^\s*REPLACE\s+INTO", "INSERT INTO", stmt, flags=re.IGNORECASE)
    if mode:
        stmt = _append_conflict_clause(stmt, mode)
    # placeholder translation: escape stray % then ? -> %s
    stmt = re.sub(r"%(?![sbt])", "%%", stmt).replace("?", "%s")
    return stmt


def _append_conflict_clause(stmt: str, mode: str) -> str:
    """Append an ON CONFLICT clause inferred from the column list."""
    m = re.match(
        r"INSERT\s+INTO\s+([^\s(]+)\s*\(([^)]*)\)\s*VALUES\s*\(",
        stmt,
        re.IGNORECASE,
    )
    if not m:
        # INSERT INTO t SELECT ... / DEFAULT VALUES — degrade to DO NOTHING
        return stmt + " ON CONFLICT DO NOTHING" if mode == "IGNORE" else stmt
    table, columns = m.group(1), [c.strip() for c in m.group(2).split(",")]
    if mode == "IGNORE":
        return stmt + " ON CONFLICT DO NOTHING"
    # REPLACE / OR REPLACE: upsert on the first column (PK convention in
    # the governed stores is single-column primary keys — verified per
    # migrated schema; multi-column PKs must spell the target out).
    if len(columns) < 2:
        return stmt + " ON CONFLICT DO NOTHING"
    target = columns[0]
    updates = ", ".join(
        f"{c} = EXCLUDED.{c}" for c in columns[1:]
    )
    return stmt + f" ON CONFLICT ({target}) DO UPDATE SET {updates}"  # sql-ok: identifiers derive from parsed INSERT column list, values parameterized


# ---------------------------------------------------------------------------
# Row / cursor / connection facade
# ---------------------------------------------------------------------------


def _split_script(script: str) -> Iterator[str]:
    """Split a multi-statement script on ``;`` while respecting ``$$``-quoted
    function bodies (PL/pgSQL) and single-quoted strings."""
    parts: list[str] = []
    current: list[str] = []
    in_dollar = False
    in_string = False
    i = 0
    while i < len(script):
        ch = script[i]
        if in_dollar:
            current.append(ch)
            if ch == "$" and script[i : i + 2] == "$$":
                current.append("$")
                in_dollar = False
                i += 1
        elif in_string:
            current.append(ch)
            if ch == "'":
                in_string = False
        else:
            if ch == "$" and script[i : i + 2] == "$$":
                in_dollar = True
                current.append(ch)
                current.append("$")
                i += 1
            elif ch == "'":
                in_string = True
                current.append(ch)
            elif ch == ";":
                statement = "".join(current).strip()
                if statement:
                    parts.append(statement)
                current = []
            else:
                current.append(ch)
        i += 1
    tail = "".join(current).strip()
    if tail:
        parts.append(tail)
    return iter(parts)


class PgRow(dict):
    """``sqlite3.Row``-compatible row: name access, positional access and
    value-order unpacking (``for a, b in row`` yields values, not keys).

    ``dict(row)`` still produces ``{column: value}`` because the row *is* a
    dict; the positional view is materialised once at construction.
    """

    __slots__ = ("_values",)

    def __init__(
        self, values: dict[str, Any], ordered: Sequence[Any] | None = None
    ) -> None:
        super().__init__(values)
        # Unnamed expressions share a column name (e.g. several COALESCE(...)
        # columns all named "coalesce"); the dict collapses duplicates, so the
        # positional view must come from the raw value sequence.
        self._values = list(ordered) if ordered is not None else list(values.values())

    def __getitem__(self, key: Any) -> Any:
        if isinstance(key, (int, slice)):
            return self._values[key]
        return super().__getitem__(key)

    def __iter__(self) -> Iterator[Any]:
        return iter(self._values)


def _pg_row_factory(cursor: Any) -> Any:
    description = cursor.description
    if description is None:
        # Statements without a result set (DDL, DML without RETURNING) still
        # ask for a factory — return raw tuples for the (empty) results.
        return tuple
    names = [column.name for column in description]

    def make_row(values: Sequence[Any]) -> PgRow:
        return PgRow(dict(zip(names, values)), ordered=values)

    return make_row


class PgCursor:
    """Minimal cursor surface: fetchone/fetchall/fetchmany/rowcount.

    Rows behave like ``sqlite3.Row``: index, name and ``keys()`` access,
    plus value-order unpacking, via :class:`PgRow`.
    """

    def __init__(self, cursor: Any) -> None:
        self._cursor = cursor

    def __iter__(self) -> Iterator[Any]:
        return iter(self._cursor)

    def fetchone(self) -> Any:
        return self._cursor.fetchone()

    def fetchall(self) -> list[Any]:
        return self._cursor.fetchall()

    def fetchmany(self, size: int) -> list[Any]:
        return self._cursor.fetchmany(size)

    @property
    def rowcount(self) -> int:
        return self._cursor.rowcount

    @property
    def lastrowid(self) -> Any:
        return getattr(self._cursor, "lastrowid", None)

    def close(self) -> None:
        self._cursor.close()

    def execute(self, statement: str, parameters: Sequence[Any] = ()) -> "PgCursor":
        translated = translate(statement)
        if not translated:
            return self
        self._cursor.execute(translated, parameters)
        return self

    def executemany(self, statement: str, seq: Iterable[Sequence[Any]]) -> "PgCursor":
        translated = translate(statement)
        if not translated:
            return self
        self._cursor.executemany(translated, list(seq))
        return self


class PgConnection:
    """sqlite3.Connection-compatible facade over a psycopg connection."""

    def __init__(self, connection: Any, schema: str) -> None:
        self._connection = connection
        self.schema = schema
        self.row_factory: Any = None  # accepted for API parity; rows are dicts

    # -- sqlite3 surface ------------------------------------------------------

    def execute(self, statement: str, parameters: Sequence[Any] = ()) -> PgCursor:
        cur = self.cursor()
        return cur.execute(statement, parameters)

    def executemany(self, statement: str, seq: Iterable[Sequence[Any]]) -> PgCursor:
        cur = self.cursor()
        return cur.executemany(statement, seq)

    def executescript(self, script: str) -> PgCursor:
        cur = self.cursor()
        for statement in _split_script(script):
            cur.execute(statement)  # sql-ok: executescript parity — bounded split of caller-owned DDL script
        return cur

    def cursor(self) -> PgCursor:
        return PgCursor(self._connection.cursor())

    def commit(self) -> None:
        self._connection.commit()

    def rollback(self) -> None:
        self._connection.rollback()

    def close(self) -> None:
        self._connection.close()

    @property
    def total_changes(self) -> int:
        return 0  # informational only in sqlite; not required by callers

    # -- context manager: sqlite3 semantics = commit on success ---------------

    def __enter__(self) -> "PgConnection":
        return self

    def __exit__(self, exc_type, exc, tb) -> bool:
        if exc_type is None:
            self._connection.commit()
        else:
            self._connection.rollback()
        return False


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def _resolve_dsn() -> str:
    """Resolve the governed runtime DSN; fail closed when unavailable."""
    try:
        from shared_layer.security.dsn_policy import (  # noqa: PLC0415
            DsnPurpose,
            resolve_dsn,
        )
        binding = resolve_dsn(DsnPurpose.RUNTIME)
        if binding.dsn.strip():
            return binding.dsn
    except Exception as exc:  # noqa: BLE001 — fail closed, never file fallback
        raise PgUnavailable(f"runtime DSN unavailable: {exc}") from exc
    raise PgUnavailable("runtime DSN unavailable: empty binding")


def connect(
    schema: str,
    *,
    dsn: str | None = None,
    autocommit: bool = True,
    connect_timeout: int = 5,
    row_factory: Any = None,
) -> PgConnection:
    """Open a PostgreSQL connection scoped to *schema*.

    ``autocommit=True`` matches sqlite3's ``isolation_level=None``; set
    False to hold transactions across statements until ``commit``.
    ``row_factory`` defaults to ``dict_row`` (``sqlite3.Row``-like named
    access); pass ``tuple_row`` for positional-only consumers.
    """
    try:
        import psycopg  # noqa: PLC0415
    except ImportError as exc:
        raise PgUnavailable("psycopg is not importable") from exc
    conn = psycopg.connect(
        dsn or _resolve_dsn(),
        autocommit=autocommit,
        connect_timeout=connect_timeout,
        row_factory=row_factory or _pg_row_factory,
    )
    conn.execute(
        "SET search_path TO " + '"' + schema.replace('"', "") + '", public'
    )
    return PgConnection(conn, schema)


__all__ = [
    "PgConnection",
    "PgCursor",
    "PgUnavailable",
    "connect",
    "translate",
]
