"""pg_adapter — PostgreSQL-backed drop-in for ``sqlite3`` call sites.

A8/A503/A610/A621: PostgreSQL is the sole structured-data authority;
SQLite is retired.  This module gives legacy ``sqlite3.connect(...)``
call sites a minimal migration surface so each store can move to
PostgreSQL without rewriting its query layer:

    # before
    connection = sqlite3.connect(path, isolation_level=None)
    connection.row_factory = sqlite3.Row
    # after
    connection = pg_adapter.connect(schema="gptbridge_mod_xingcheng")

Supported surface (what the governed stores actually use):

* ``connect(...)`` -> :class:`PgConnection` with ``execute``,
  ``executemany``, ``executescript``, ``commit``, ``rollback``,
  ``close``, context-manager protocol and ``row_factory``-style dict
  rows (``cursor.description`` named access).
* Statement translation: ``?`` -> ``%s``, ``INSERT OR REPLACE`` ->
  ``INSERT ... ON CONFLICT DO UPDATE`` (column list preserved, conflict
  target = the table's primary key), ``INSERT OR IGNORE`` ->
  ``ON CONFLICT DO NOTHING``, ``REPLACE INTO`` -> upsert,
  ``BEGIN IMMEDIATE``/``BEGIN DEFERRED`` -> ``BEGIN``,
  ``sqlite_master`` -> ``information_schema``, ``PRAGMA`` -> no-op
  (``journal_mode``/``synchronous``/``foreign_keys`` etc. — PG
  equivalents are server-side or already enforced), ``datetime('now')``
  -> ``now()``, ``AUTOINCREMENT``/``INTEGER PRIMARY KEY`` ->
  ``GENERATED BY DEFAULT AS IDENTITY``.
* Fail-closed: no DSN -> :class:`PgUnavailable` (never a silent local
  file fallback — that was the sqlite anti-pattern this removes).

NOT a general SQL transpiler — it covers the governed store surface;
callers that exercise exotic sqlite-isms must translate explicitly.

Split layout (source-size contract): ``pg_adapter_pool`` owns the bounded
connection pool, ``pg_adapter_translate`` the statement rewriter,
``pg_adapter_rows``/``pg_adapter_cursor``/``pg_adapter_connection`` the
sqlite3-compatible facade classes; this module keeps the entry surface.
"""

from __future__ import annotations

from typing import Any

from .pg_adapter_connection import PgConnection
from .pg_adapter_cursor import PgCursor
from .pg_adapter_pool import (
    _pool_checkout,
    _pool_enabled,
    close_pool,
)
from .pg_adapter_rows import _pg_row_factory
from .pg_adapter_translate import translate


class PgUnavailable(RuntimeError):
    """Raised when no governed PostgreSQL DSN is resolvable."""


def _resolve_dsn() -> str:
    """Resolve the governed runtime DSN; fail closed when unavailable."""
    try:
        from shared_layer.security.dsn_policy import (  # noqa: PLC0415
            DsnPurpose,
            resolve_dsn,
        )
        binding = resolve_dsn(DsnPurpose.RUNTIME)
        if binding.dsn.strip():
            return binding.dsn
    except Exception as exc:  # noqa: BLE001 — fail closed, never file fallback
        raise PgUnavailable(f"runtime DSN unavailable: {exc}") from exc
    raise PgUnavailable("runtime DSN unavailable: empty binding")


def connect(
    schema: str,
    *,
    dsn: str | None = None,
    autocommit: bool = True,
    connect_timeout: int = 5,
    row_factory: Any = None,
) -> PgConnection:
    """Open a PostgreSQL connection scoped to *schema*.

    ``autocommit=True`` matches sqlite3's ``isolation_level=None``; set
    False to hold transactions across statements until ``commit``.
    ``row_factory`` defaults to ``dict_row`` (``sqlite3.Row``-like named
    access); pass ``tuple_row`` for positional-only consumers.
    """
    try:
        import psycopg  # noqa: PLC0415
    except ImportError as exc:
        raise PgUnavailable("psycopg is not importable") from exc
    resolved_dsn = dsn or _resolve_dsn()
    pool_key: tuple[Any, ...] | None = (
        (resolved_dsn, schema, bool(autocommit), row_factory)
        if _pool_enabled()
        else None
    )
    conn = _pool_checkout(pool_key) if pool_key is not None else None
    if conn is None:
        conn = psycopg.connect(
            resolved_dsn,
            autocommit=autocommit,
            connect_timeout=connect_timeout,
            row_factory=row_factory or _pg_row_factory,
        )
    # SET lives inside the caller's transaction for autocommit=False
    # connections — a rollback reverts it.  Re-applying on every checkout
    # (and fresh connect) keeps pooled connections self-healing instead of
    # permanently serving the default "$user", public search path.
    conn.execute(
        "SET search_path TO " + '"' + schema.replace('"', "") + '", public'
    )
    return PgConnection(conn, schema, pool_key)


__all__ = [
    "PgConnection",
    "PgCursor",
    "PgUnavailable",
    "close_pool",
    "connect",
    "translate",
]
