"""Sorter engine facade — re-exports the decomposed domain modules."""

from __future__ import annotations

from .sorter_types import (
    DEFAULT_EXCLUDE,
    DEFAULT_INCLUDE,
    DEFAULT_JOURNAL_RETENTION_DAYS,
    DEFAULT_PLAN_TTL_SECONDS,
    DEFAULT_QUIET_SECONDS,
    FileFingerprint,
    JOURNAL_RETENTION_DAYS_ENV,
    OrganizePlan,
    PARTIAL_SUFFIXES,
    PlanOperation,
    ProfileSnapshot,
    RuleConflictError,
    SCHEMA_VERSION,
    STATE_ROOT_ENV,
    SkippedFile,
    SorterV2Error,
    StabilityResult,
    TERMINAL_TRANSACTION_STATES,
    TOOL_ROOT,
    _FileMetadata,
    _SAFE_ID_RE,
    _TARGET_LOCKS_GUARD,
    _TARGET_LOCKS_HELD,
    _utc_after,
    _utc_now,
    _validated_id,
    sha256_file,
)
from .sorter_paths import (
    _clean_patterns,
    _clean_rule_dicts,
    _is_link_or_reparse,
    _plan_expired,
    _same_path_identity,
    _state_category_root,
    _validate_journal_operation_paths,
    _validate_operation_paths,
    _validated_state_document_path,
    _validated_target_directory,
    profile_id_for,
    profile_path,
    resolve_state_root,
)
from .sorter_locks import (
    _ExclusiveFileLock,
    _TargetDirectoryLock,
    _atomic_write_json,
    _fsync_directory,
    _lock_owner_alive,
    _try_lock_descriptor,
    _unlock_descriptor,
    _windows_process_alive,
)
from .sorter_profiles import (
    _profile_document,
    _read_profile_document,
    list_profiles,
    load_profile,
    save_profile,
)
from .sorter_stability import (
    _best_effort_unlocked,
    check_file_stability,
    is_partial_file,
    same_volume,
)
from .sorter_plans import (
    _document_age_days,
    _journal_retention_days,
    load_plan,
    new_plan,
    prune_state,
    save_plan,
)
from .sorter_journal import (
    _Journal,
    _journal_path,
    _read_journal,
    transaction_history,
)
from .sorter_metadata import (
    _capture_file_metadata,
    _copy_windows_exclusive,
    _ensure_source_unchanged,
    _expected_fingerprint,
    _file_metadata_from_dict,
    _file_metadata_to_dict,
    _fingerprint,
    _fsync_file,
    _posix_extended_attributes,
    _set_windows_file_attributes,
    _unlink_file_preserving_failure,
    _verify_file_metadata,
    _windows_alternate_streams,
)
from .sorter_staging import (
    _copy_file_exclusive_preserving_metadata,
    _copy_stage_exclusive,
    _copy_to_staging,
    _publish_staging,
    _same_volume_move,
    _staged_move,
)
from .sorter_execute import (
    _execute_plan_under_lock,
    _existing_plan_execution,
    _target_lock_path,
    execute_plan,
)
from .sorter_undo_move import (
    _move_exact_for_undo,
    _resume_undo_move,
    _validate_undo_move_paths,
)
from .sorter_undo import (
    _journal_has_interrupted_undo,
    _recover_journal,
    _undo_journal,
    _undo_transaction_under_lock,
    recover_transactions,
    undo_last_transaction,
    undo_transaction,
)

__all__ = [
    "DEFAULT_EXCLUDE",
    "DEFAULT_INCLUDE",
    "DEFAULT_JOURNAL_RETENTION_DAYS",
    "DEFAULT_PLAN_TTL_SECONDS",
    "DEFAULT_QUIET_SECONDS",
    "FileFingerprint",
    "JOURNAL_RETENTION_DAYS_ENV",
    "OrganizePlan",
    "PARTIAL_SUFFIXES",
    "PlanOperation",
    "ProfileSnapshot",
    "RuleConflictError",
    "SCHEMA_VERSION",
    "STATE_ROOT_ENV",
    "SkippedFile",
    "SorterV2Error",
    "StabilityResult",
    "TERMINAL_TRANSACTION_STATES",
    "TOOL_ROOT",
    "check_file_stability",
    "execute_plan",
    "is_partial_file",
    "list_profiles",
    "load_plan",
    "load_profile",
    "new_plan",
    "profile_id_for",
    "profile_path",
    "prune_state",
    "recover_transactions",
    "resolve_state_root",
    "same_volume",
    "save_plan",
    "save_profile",
    "sha256_file",
    "transaction_history",
    "undo_last_transaction",
    "undo_transaction",
]
