"""PostgreSQL lifecycle for GPTBridge's canonical structured data.

PostgreSQL owns central structured data, shared transport, and audit roles.
The local SQLite package is limited to owner-private state and bounded,
observable degraded operation that must reconcile back to PostgreSQL.
Members remain lazy so health inspection does not require an eager connection.
"""

from __future__ import annotations

from typing import Any

POSTGRESQL_CANONICAL: bool = True

_LAZY_EXPORTS = {
    "BootstrapReport": ("bootstrap", "BootstrapReport"),
    "DatabaseBootstrap": ("bootstrap", "DatabaseBootstrap"),
    "BackupOrchestrator": ("backup", "BackupOrchestrator"),
    "BackupResult": ("backup", "BackupResult"),
    "DatabaseSettings": ("config", "DatabaseSettings"),
    "ConnectionManager": ("connection", "ConnectionManager"),
    "PostgreSQLDetection": ("detection", "PostgreSQLDetection"),
    "detect_postgresql": ("detection", "detect_postgresql"),
    "DatabaseHealth": ("health", "DatabaseHealth"),
    "DatabaseHealthCheck": ("health", "DatabaseHealthCheck"),
    "PostgreSQLPool": ("pool", "PostgreSQLPool"),
    "set_provenance": ("provenance", "set_provenance"),
    "clear_provenance": ("provenance", "clear_provenance"),
    "set_contract_version": ("provenance", "set_contract_version"),
    "set_migration_executor": ("provenance", "set_migration_executor"),
    "clear_migration_executor": ("provenance", "clear_migration_executor"),
    "capture_snapshot": ("permission_snapshot", "capture_snapshot"),
    "get_current_generation": ("generation_fence", "get_current_generation"),
    "bump_generation": ("generation_fence", "bump_generation"),
    "is_connection_stale": ("generation_fence", "is_connection_stale"),
    "get_stale_sqlite_databases": ("generation_fence", "get_stale_sqlite_databases"),
    "upsert_sqlite_generation": ("generation_fence", "upsert_sqlite_generation"),
    "get_stale_qdrant_collections": ("generation_fence", "get_stale_qdrant_collections"),
    "upsert_qdrant_generation": ("generation_fence", "upsert_qdrant_generation"),
    "sync_qdrant_generation": ("generation_fence", "sync_qdrant_generation"),
    "tombstone": ("deletion_coordinator", "tombstone"),
    "advance_stage": ("deletion_coordinator", "advance_stage"),
    "get_purge_eligible": ("deletion_coordinator", "get_purge_eligible"),
    "scan_orphans": ("orphan_scanner", "scan_orphans"),
    "certify_rebuild": ("rebuild_certifier", "certify"),
    "certify_rebuild_engine": ("rebuild_certifier", "certify_engine"),
    "is_rebuild_certified": ("rebuild_certifier", "is_certified"),
    "check_long_transactions": ("watchdog", "check_long_transactions"),
    "collect_bloat_report": ("watchdog", "collect_bloat_report"),
    "get_rpo_rto_classes": ("watchdog", "get_rpo_rto_classes"),
    "get_capacity_thresholds": ("watchdog", "get_capacity_thresholds"),
    "terminate_long_transactions": ("watchdog", "terminate_long_transactions"),
    "collect_bloat_transport": ("watchdog", "collect_bloat_transport"),
    "collect_bloat_audit": ("watchdog", "collect_bloat_audit"),
    "certify_startup": ("startup_certifier", "certify_startup"),
    "is_database_ready": ("startup_certifier", "is_ready"),
    "set_domain_readonly": ("readonly_domain", "set_readonly"),
    "is_domain_readonly": ("readonly_domain", "is_readonly"),
    "record_query_fingerprint": ("query_fingerprint", "record"),
    "get_hot_queries": ("query_fingerprint", "get_hot"),
    "apply_sqlite_pragma": ("sqlite_pragma_policy", "apply_pragma"),
    "get_sqlite_pragma_policy": ("sqlite_pragma_policy", "get_pragma_policy"),
    "register_sqlite_class": ("sqlite_classification", "register"),
    "get_sqlite_class": ("sqlite_classification", "get_class"),
    "list_sqlite_by_class": ("sqlite_classification", "list_by_class"),
    "check_and_checkpoint": ("sqlite_wal_governor", "check_and_checkpoint"),
    "get_wal_stats": ("sqlite_wal_governor", "get_wal_stats"),
    "BatchWriter": ("batch_writer", "BatchWriter"),
    "LocatorCache": ("locator_cache", "LocatorCache"),
    "get_default_locator_cache": ("locator_cache", "get_default_cache"),
    "record_baseline": ("performance_baseline", "record"),
    "get_latest_baseline": ("performance_baseline", "get_latest"),
    "compare_baseline": ("performance_baseline", "compare"),
    "load_release_manifest": ("release_manifest", "load_manifest"),
    "validate_runtime_compatibility": ("release_manifest", "validate_runtime"),
    "get_release_compatibility_matrix": ("release_manifest", "get_compatibility_matrix"),
    "transition_lifecycle_state": ("lifecycle_manager", "transition_state"),
    "get_lifecycle_state": ("lifecycle_manager", "get_state"),
    "enqueue_purge": ("lifecycle_manager", "enqueue_purge"),
    "get_purge_eligible": ("lifecycle_manager", "get_purge_eligible"),
    "check_resource_dependencies": ("lifecycle_manager", "check_dependencies"),
    "record_purge_audit": ("lifecycle_manager", "record_purge"),
    "place_retention_hold": ("lifecycle_manager", "place_hold"),
    "release_retention_hold": ("lifecycle_manager", "release_hold"),
    "has_active_retention_hold": ("lifecycle_manager", "has_active_hold"),
    "register_archive_catalog": ("lifecycle_manager", "register_archive"),
    # Phase H: integrity verification
    "populate_event_hash_chain": ("integrity_verifier", "populate_event_hash_chain"),
    "verify_audit_chain": ("integrity_verifier", "verify_audit_chain"),
    "get_audit_head_hash": ("integrity_verifier", "get_audit_head_hash"),
    "start_reconcile_batch": ("integrity_verifier", "start_reconcile_batch"),
    "complete_reconcile_batch": ("integrity_verifier", "complete_reconcile_batch"),
    "record_resource_content_hash": ("integrity_verifier", "record_resource_hash"),
    "verify_resource_content_hash": ("integrity_verifier", "verify_resource_hash"),
    "record_sqlite_database_digest": ("integrity_verifier", "record_sqlite_digest"),
    "record_qdrant_integrity_mapping": ("integrity_verifier", "record_qdrant_integrity"),
    "verify_qdrant_integrity_mapping": ("integrity_verifier", "verify_qdrant_integrity"),
    "record_merkle_root": ("integrity_verifier", "record_merkle_root"),
    "create_integrity_snapshot": ("integrity_verifier", "create_integrity_snapshot"),
    "record_restore_verification": ("integrity_verifier", "record_restore_verification"),
    "record_tamper_state": ("integrity_verifier", "record_tamper_state"),
    "trigger_fail_closed": ("integrity_verifier", "trigger_fail_closed"),
    "is_fail_closed_active": ("integrity_verifier", "is_fail_closed_active"),
    # Phase I: dependency & version governance
    "lock_version": ("dependency_governor", "lock_version"),
    "get_version_lock": ("dependency_governor", "get_version_lock"),
    "record_compatibility": ("dependency_governor", "record_compatibility"),
    "check_combination_allowed": ("dependency_governor", "check_combination_allowed"),
    "classify_upgrade": ("dependency_governor", "classify_upgrade"),
    "get_upgrade_class": ("dependency_governor", "get_upgrade_class"),
    "record_driver_test": ("dependency_governor", "record_driver_test"),
    "is_driver_version_verified": ("dependency_governor", "is_driver_version_verified"),
    "start_pg_rehearsal": ("dependency_governor", "start_pg_rehearsal"),
    "advance_pg_rehearsal": ("dependency_governor", "advance_pg_rehearsal"),
    "record_sqlite_runtime_compat": ("dependency_governor", "record_sqlite_runtime_compat"),
    "record_qdrant_compat": ("dependency_governor", "record_qdrant_compat"),
    "record_sbom_entry": ("dependency_governor", "record_sbom_entry"),
    "record_vulnerability": ("dependency_governor", "record_vulnerability"),
    "record_dependency_drift": ("dependency_governor", "record_dependency_drift"),
    "register_offline_bundle": ("dependency_governor", "register_offline_bundle"),
    "sign_release": ("dependency_governor", "sign_release"),
    "verify_release_signature": ("dependency_governor", "verify_release_signature"),
    # Central lineage (migration 086)
    "ensure_transformation": ("lineage", "ensure_transformation"),
    "register_lineage_node": ("lineage", "register_node"),
    "relate": ("lineage", "relate"),
    "invalidate": ("lineage", "invalidate"),
    "reverse_lookup": ("lineage", "reverse_lookup"),
    "impact": ("lineage", "impact"),
    "health_check_lineage": ("lineage", "health_check"),
    "record_rag_resource": ("lineage", "record_rag_resource"),
    "record_qdrant_point": ("lineage", "record_qdrant_point"),
    "record_reconcile_lineage": ("lineage", "record_reconcile"),
    "record_restore_lineage": ("lineage", "record_restore"),
    # Phase J: recovery orchestration
    "register_recovery_plan": ("recovery_orchestrator", "register_recovery_plan"),
    "open_recovery_incident": ("recovery_orchestrator", "open_recovery_incident"),
    "transition_recovery_state": ("recovery_orchestrator", "transition_recovery_state"),
    "create_recovery_generation": ("recovery_orchestrator", "create_recovery_generation"),
    "get_current_generation": ("recovery_orchestrator", "get_current_generation"),
    "start_pg_offline_recovery": ("recovery_orchestrator", "start_pg_offline_recovery"),
    "confirm_pg_failure": ("recovery_orchestrator", "confirm_pg_failure"),
    "record_pg_recovery_verification": ("recovery_orchestrator", "record_pg_recovery_verification"),
    "is_pg_recoverable": ("recovery_orchestrator", "is_pg_recoverable"),
    "register_unknown_commit": ("recovery_orchestrator", "register_unknown_commit"),
    "resolve_commit_state": ("recovery_orchestrator", "resolve_commit_state"),
    "check_lease_expiry": ("recovery_orchestrator", "check_lease_expiry"),
    "reclaim_lease": ("recovery_orchestrator", "reclaim_lease"),
    "raise_recovery_barrier": ("recovery_orchestrator", "raise_recovery_barrier"),
    "is_recovery_barrier_active": ("recovery_orchestrator", "is_recovery_barrier_active"),
    "release_recovery_barrier": ("recovery_orchestrator", "release_recovery_barrier"),
    "save_recovery_checkpoint": ("recovery_orchestrator", "save_recovery_checkpoint"),
    "check_or_mark_idempotent": ("recovery_orchestrator", "check_or_mark_idempotent"),
    "mark_idempotent_complete": ("recovery_orchestrator", "mark_idempotent_complete"),
    "check_safety_fence": ("recovery_orchestrator", "check_safety_fence"),
    "record_fence_block": ("recovery_orchestrator", "record_fence_block"),
    "is_recovery_plan_certified": ("recovery_orchestrator", "is_recovery_plan_certified"),
    "start_chaos_drill": ("recovery_orchestrator", "start_chaos_drill"),
    "complete_chaos_drill": ("recovery_orchestrator", "complete_chaos_drill"),
    # Phase K: data layer contract
    "register_data_layer_contract": ("data_layer_contract", "register_data_layer_contract"),
    "activate_data_layer_contract": ("data_layer_contract", "activate_data_layer_contract"),
    "get_active_data_layer_contract": ("data_layer_contract", "get_active_data_layer_contract"),
    "classify_dependency": ("data_layer_contract", "classify_dependency"),
    "get_dependency_classification": ("data_layer_contract", "get_dependency_classification"),
    "get_startup_order": ("data_layer_contract", "get_startup_order"),
    "get_shutdown_order": ("data_layer_contract", "get_shutdown_order"),
    "register_startup_gate": ("data_layer_contract", "register_startup_gate"),
    "set_gate_result": ("data_layer_contract", "set_gate_result"),
    "is_phase_complete": ("data_layer_contract", "is_phase_complete"),
    "can_enable_write": ("data_layer_contract", "can_enable_write"),
    "set_schema_readiness": ("data_layer_contract", "set_schema_readiness"),
    "is_schema_ready": ("data_layer_contract", "is_schema_ready"),
    "is_pg_certified": ("data_layer_contract", "is_pg_certified"),
    "can_enable_business_write": ("data_layer_contract", "can_enable_business_write"),
    "evaluate_rag_readiness": ("data_layer_contract", "evaluate_rag_readiness"),
    "is_rag_ready": ("data_layer_contract", "is_rag_ready"),
    "start_shutdown_audit": ("data_layer_contract", "start_shutdown_audit"),
    "complete_shutdown_audit": ("data_layer_contract", "complete_shutdown_audit"),
    "was_last_shutdown_graceful": ("data_layer_contract", "was_last_shutdown_graceful"),
    "detect_unclean_shutdown": ("data_layer_contract", "detect_unclean_shutdown"),
    "mark_unclean_step_done": ("data_layer_contract", "mark_unclean_step_done"),
    "is_unclean_recovery_complete": ("data_layer_contract", "is_unclean_recovery_complete"),
    "register_cache_policy": ("data_layer_contract", "register_cache_policy"),
    "should_invalidate_cache": ("data_layer_contract", "should_invalidate_cache"),
    "get_dependencies": ("data_layer_contract", "get_dependencies"),
    "get_dependents": ("data_layer_contract", "get_dependents"),
    "get_integration_rules": ("data_layer_contract", "get_integration_rules"),
    "check_integration_rule": ("data_layer_contract", "check_integration_rule"),
    "get_capability_degradation_matrix": (
        "data_layer_contract",
        "get_capability_degradation_matrix",
    ),
    # Read models / CQRS boundary (migration 087)
    "ConsistencyLevel": ("readmodel", "ConsistencyLevel"),
    "ReadModelClient": ("readmodel", "ReadModelClient"),
    "AuthoritativeCache": ("readmodel", "AuthoritativeCache"),
    "SecuritySnapshotCache": ("readmodel", "SecuritySnapshotCache"),
    "ReadModelMaintainer": ("readmodel", "ReadModelMaintainer"),
    "refresh_projection": ("readmodel", "refresh_projection"),
    "start_projection_build": ("readmodel", "start_projection_build"),
    "compute_projection_rows": ("readmodel", "compute_projection_rows"),
    "publish_projection_build": ("readmodel", "publish_projection_build"),
    "drop_projection": ("readmodel", "drop_projection"),
    "watermark_read_model": ("readmodel", "watermark"),
    "get_projection_lag": ("readmodel", "get_projection_lag"),
    "get_projection_lag_map": ("readmodel", "get_projection_lag_map"),
    "refresh_projections": ("readmodel", "refresh_projections"),
    "read_projection": ("readmodel", "read_projection"),
    "mark_sqlite_cache": ("readmodel", "mark_sqlite_cache"),
    # RAG capacity governance (migration 088)
    "RagCapacityPolicy": ("rag_capacity", "RagCapacityPolicy"),
    "DEFAULT_CAPACITY_POLICY": ("rag_capacity", "DEFAULT_CAPACITY_POLICY"),
    "QueueStateRag": ("rag_capacity", "QueueState"),
    "QueueDecisionRag": ("rag_capacity", "QueueDecision"),
    "AgenticStop": ("rag_capacity", "AgenticStop"),
    "pool_for_operation": ("rag_capacity", "pool_for_operation"),
    "current_capacity_policy": ("rag_capacity", "current_capacity_policy"),
    "upsert_capacity_policy": ("rag_capacity", "upsert_capacity_policy"),
    "set_queue_state": ("rag_capacity", "set_queue_state"),
    "queue_admission": ("rag_capacity", "queue_admission"),
    "record_phase_latency": ("rag_capacity", "record_phase_latency"),
    "record_retrieval_trace": ("rag_capacity", "record_retrieval_trace"),
    "initialize_generation": ("rag_capacity", "initialize_generation"),
    "advance_generation": ("rag_capacity", "advance_generation"),
    "list_rag_slo": ("rag_capacity", "list_rag_slo"),
    "admit": ("rag_capacity", "admit"),
    "build_qdrant_filter": ("rag_capacity", "build_qdrant_filter"),
    "select_index_profile": ("rag_capacity", "select_index_profile"),
    "reranker_batches": ("rag_capacity", "reranker_batches"),
    "enforce_diversity": ("rag_capacity", "enforce_diversity"),
    "merge_adjacent_chunks": ("rag_capacity", "merge_adjacent_chunks"),
    "agentic_stop_reason": ("rag_capacity", "agentic_stop_reason"),
    "has_new_evidence": ("rag_capacity", "has_new_evidence"),
    "retrieval_cache_key": ("rag_capacity", "retrieval_cache_key"),
    "EmbeddingCache": ("rag_capacity", "EmbeddingCache"),
    "RetrievalCache": ("rag_capacity", "RetrievalCache"),
    # Database Auto Maintenance v1
    "MaintenanceRiskClass": ("maintenance.models", "MaintenanceRiskClass"),
    "MaintenanceJobStatus": ("maintenance.models", "MaintenanceJobStatus"),
    "MaintenanceJob": ("maintenance.models", "MaintenanceJob"),
    "MaintenanceReasonCode": ("maintenance.models", "MaintenanceReasonCode"),
    "MaintenanceAction": ("maintenance.registry", "MaintenanceAction"),
    "MaintenanceRegistry": ("maintenance.registry", "MaintenanceRegistry"),
    "get_maintenance_registry": ("maintenance.registry", "get_registry"),
    "register_maintenance_action": ("maintenance.registry", "register_action"),
    "MaintenancePolicy": ("maintenance.policies", "MaintenancePolicy"),
    "MaintenanceDecision": ("maintenance.policies", "MaintenanceDecision"),
    "evaluate_maintenance_policy": ("maintenance.policies", "evaluate_policy"),
    "SystemRecoveryState": ("maintenance.policies", "SystemRecoveryState"),
    "MaintenanceBudget": ("maintenance.budgets", "MaintenanceBudget"),
    "BudgetConfig": ("maintenance.budgets", "BudgetConfig"),
    "BudgetState": ("maintenance.budgets", "BudgetState"),
    "check_maintenance_budget": ("maintenance.budgets", "check_budget"),
    "MaintenanceLease": ("maintenance.leases", "MaintenanceLease"),
    "LeaseManager": ("maintenance.leases", "LeaseManager"),
    "acquire_maintenance_lease": ("maintenance.leases", "acquire_lease"),
    "renew_maintenance_lease": ("maintenance.leases", "renew_lease"),
    "release_maintenance_lease": ("maintenance.leases", "release_lease"),
    "recover_expired_maintenance_leases": ("maintenance.leases", "recover_expired_leases"),
    "MaintenanceCandidate": ("maintenance.evaluator", "MaintenanceCandidate"),
    "Evaluator": ("maintenance.evaluator", "Evaluator"),
    "evaluate_maintenance_candidates": ("maintenance.evaluator", "evaluate_candidates"),
    "MaintenanceScheduler": ("maintenance.scheduler", "MaintenanceScheduler"),
    "SchedulerConfig": ("maintenance.scheduler", "SchedulerConfig"),
    "schedule_maintenance_candidates": ("maintenance.scheduler", "schedule_candidates"),
    "MaintenanceController": ("maintenance.controller", "MaintenanceController"),
    "ControllerConfig": ("maintenance.controller", "ControllerConfig"),
    "run_maintenance_controller": ("maintenance.controller", "run_maintenance_cycle"),
    "VerificationResult": ("maintenance.verifier", "VerificationResult"),
    "Verifier": ("maintenance.verifier", "Verifier"),
    "verify_maintenance_action": ("maintenance.verifier", "verify_action"),
    "get_maintenance_verifier": ("maintenance.verifier", "get_verifier"),
    # Maintenance engine modules
    "collect_pg_health": ("maintenance.maintenance_postgres", "collect_pg_health"),
    "collect_pg_pool_pressure": ("maintenance.maintenance_postgres", "collect_pool_pressure"),
    "collect_pg_lock_pressure": ("maintenance.maintenance_postgres", "collect_lock_pressure"),
    "collect_pg_statistics_freshness": ("maintenance.maintenance_postgres", "collect_statistics_freshness"),
    "collect_pg_growth": ("maintenance.maintenance_postgres", "collect_growth_observation"),
    "execute_pg_analyze": ("maintenance.maintenance_postgres", "execute_pg_analyze"),
    "execute_pg_health_observe": ("maintenance.maintenance_postgres", "execute_pg_health_observe"),
    "build_pg_maintenance_signals": ("maintenance.maintenance_postgres", "build_pg_signals"),
    "get_pg_maintenance_executors": ("maintenance.maintenance_postgres", "get_pg_maintenance_executors"),
    "collect_sqlite_health": ("maintenance.maintenance_sqlite", "collect_sqlite_health"),
    "execute_sqlite_checkpoint": ("maintenance.maintenance_sqlite", "execute_sqlite_checkpoint"),
    "execute_sqlite_health_observe": ("maintenance.maintenance_sqlite", "execute_sqlite_health_observe"),
    "build_sqlite_maintenance_signals": ("maintenance.maintenance_sqlite", "build_sqlite_signals"),
    "get_sqlite_maintenance_executors": ("maintenance.maintenance_sqlite", "get_sqlite_maintenance_executors"),
    "collect_reconcile_state": ("maintenance.maintenance_reconcile", "collect_reconcile_state"),
    "evaluate_reconcile_adjustment": ("maintenance.maintenance_reconcile", "evaluate_reconcile_adjustment"),
    "apply_reconcile_adjustment": ("maintenance.maintenance_reconcile", "apply_reconcile_adjustment"),
    "execute_reconcile_throttle": ("maintenance.maintenance_reconcile", "execute_reconcile_throttle"),
    "execute_reconcile_health_observe": ("maintenance.maintenance_reconcile", "execute_reconcile_health_observe"),
    "build_reconcile_maintenance_signals": ("maintenance.maintenance_reconcile", "build_reconcile_signals"),
    "get_reconcile_maintenance_executors": ("maintenance.maintenance_reconcile", "get_reconcile_maintenance_executors"),
    "collect_backup_info": ("maintenance.maintenance_backup", "collect_backup_info"),
    "execute_backup_verify": ("maintenance.maintenance_backup", "execute_backup_verify"),
    "execute_backup_health_observe": ("maintenance.maintenance_backup", "execute_backup_health_observe"),
    "build_backup_maintenance_signals": ("maintenance.maintenance_backup", "build_backup_signals"),
    "get_backup_maintenance_executors": ("maintenance.maintenance_backup", "get_backup_maintenance_executors"),
}

__all__ = ["POSTGRESQL_CANONICAL", *_LAZY_EXPORTS]


def __getattr__(name: str) -> Any:
    entry = _LAZY_EXPORTS.get(name)
    if entry is None:
        raise AttributeError(f"module 'shared_layer.database' has no attribute {name!r}")
    module_name, member = entry
    module = __import__(
        f"shared_layer.database.{module_name}", fromlist=[member]
    )
    return getattr(module, member)