"""Declared governance table contracts (Phase I dependency/version, J recovery, K data-layer)."""
from __future__ import annotations

from .schema_contract_registry_types import TableContract


DECLARED_TABLES_GOVERNANCE: tuple[TableContract, ...] = (
    # Phase I: dependency & version governance
    TableContract(
        schema="gptbridge_index",
        table="version_lock",
        columns=(
            "lock_id", "release_id", "component", "major_version",
            "minor_version", "patch_version", "version_string",
            "locked_at", "locked_by", "description",
        ),
        indexes=("version_lock_release_idx", "version_lock_component_idx"),
    ),
    TableContract(
        schema="gptbridge_index",
        table="compatibility_matrix_ext",
        columns=(
            "matrix_id", "release_id", "postgresql_version",
            "psycopg_version",
            "vectord_server_version", "vectord_client_version",
            "python_version", "status", "tested_at", "tested_by",
            "test_result", "notes", "updated_at",
        ),
        indexes=("compat_matrix_ext_release_idx", "compat_matrix_ext_status_idx"),
    ),
    TableContract(
        schema="gptbridge_index",
        table="upgrade_classification",
        columns=(
            "classification_id", "component", "from_version", "to_version",
            "upgrade_class", "required_validation", "allows_unattended",
            "requires_backup", "requires_clone_test",
            "requires_certification", "rollback_allowed",
            "description", "classified_by", "classified_at",
        ),
        indexes=("upgrade_class_component_idx", "upgrade_class_class_idx"),
    ),
    TableContract(
        schema="gptbridge_index",
        table="driver_compatibility_test",
        columns=(
            "test_id", "driver_name", "driver_version", "test_category",
            "passed", "tested_at", "tested_by", "test_details",
            "failure_reason", "duration_ms",
        ),
        indexes=("driver_compat_driver_idx", "driver_compat_passed_idx"),
    ),
    TableContract(
        schema="gptbridge_index",
        table="pg_major_upgrade_rehearsal",
        columns=(
            "rehearsal_id", "from_version", "to_version", "status",
            "started_at", "completed_at", "backup_id", "clone_database",
            "migration_check_passed", "rls_check_passed",
            "transport_test_passed", "reconcile_test_passed",
            "performance_baseline_id", "certification_id",
            "failure_reason", "rehearsal_log",
        ),
        indexes=("pg_rehearsal_status_idx", "pg_rehearsal_version_idx"),
    ),
    TableContract(
        schema="gptbridge_index",
        table="sbom_dependency_inventory",
        columns=(
            "sbom_id", "release_id", "component", "component_type",
            "version", "source", "source_hash", "install_path",
            "license_name", "verified", "verified_at", "verified_by",
            "notes", "created_at",
        ),
        indexes=("sbom_release_idx", "sbom_component_idx", "sbom_verified_idx"),
    ),
    TableContract(
        schema="gptbridge_index",
        table="vulnerability_risk",
        columns=(
            "vuln_id", "component", "affected_versions", "fixed_version",
            "cve_id", "risk_level", "recommended_action",
            "upgrade_deadline_days", "description", "detected_at",
            "resolved_at", "resolved_by", "resolution_notes",
        ),
        indexes=("vuln_risk_component_idx", "vuln_risk_unresolved_idx"),
    ),
    TableContract(
        schema="gptbridge_index",
        table="dependency_drift",
        columns=(
            "drift_id", "release_id", "component", "expected_version",
            "installed_version", "drift_status", "detected_at",
            "detected_by", "resolved_at", "resolved_by", "resolution",
        ),
        indexes=("dep_drift_status_idx", "dep_drift_component_idx"),
    ),
    TableContract(
        schema="gptbridge_index",
        table="offline_bundle",
        columns=(
            "bundle_id", "release_id", "component", "version",
            "package_type", "platform", "storage_locator", "file_hash",
            "file_size_bytes", "hash_algorithm", "verified",
            "verified_at", "verified_by", "created_at", "notes",
        ),
        indexes=("offline_bundle_release_idx", "offline_bundle_component_idx"),
    ),
    TableContract(
        schema="gptbridge_index",
        table="release_signature",
        columns=(
            "signature_id", "release_id", "bundle_hash", "component_count",
            "component_hashes", "signature_algorithm", "signed_by",
            "signed_at", "verified_at", "verified_by",
            "verification_result", "tamper_state",
        ),
        indexes=("release_sig_release_idx", "release_sig_tamper_idx"),
    ),
    # Phase J: recovery orchestration
    TableContract(
        schema="gptbridge_index",
        table="recovery_plan",
        columns=(
            "plan_id", "version", "incident_type", "full_plan_id",
            "preconditions", "steps", "timeouts", "rollback_strategy",
            "verification_rules", "required_authority", "status",
            "created_at", "certified_at", "certified_by", "updated_at",
        ),
        indexes=("recovery_plan_incident_idx", "recovery_plan_status_idx"),
    ),
    TableContract(
        schema="gptbridge_index",
        table="recovery_incident",
        columns=(
            "incident_id", "plan_id", "incident_type", "detected_at",
            "detected_by", "description", "affected_components",
            "severity", "status", "recovery_generation",
            "degraded_generation", "resolved_generation",
            "resolved_at", "resolved_by", "resolution_notes",
            "incident_log", "updated_at",
        ),
        indexes=("recovery_incident_status_idx", "recovery_incident_type_idx"),
    ),
    TableContract(
        schema="gptbridge_index",
        table="recovery_state_machine",
        columns=(
            "state_id", "incident_id", "from_state", "to_state",
            "transition_at", "transitioned_by", "reason",
        ),
        indexes=("recovery_state_incident_idx",),
    ),
    TableContract(
        schema="gptbridge_index",
        table="recovery_state_transition",
        columns=("from_state", "to_state", "allowed", "requires_authority"),
        indexes=(),
    ),
    TableContract(
        schema="gptbridge_index",
        table="pg_offline_recovery",
        columns=(
            "recovery_id", "incident_id", "failure_detected_at",
            "confirmed_at", "confirmation_attempts", "degraded_at",
            "recovered_at", "degraded_generation", "recovered_generation",
            "modules_on_fallback", "fallback_status", "notes",
        ),
        indexes=("pg_offline_status_idx",),
    ),
    TableContract(
        schema="gptbridge_index",
        table="pg_recovery_verification",
        columns=(
            "verification_id", "incident_id", "verified_at", "verified_by",
            "connection_ok", "schema_version_ok", "database_release_ok",
            "roles_ok", "rls_ok", "audit_ok", "transport_ok",
            "integrity_ok", "generation_ok", "overall_recoverable",
            "failure_reason",
        ),
        indexes=("pg_recovery_verify_incident_idx",),
    ),
    TableContract(
        schema="gptbridge_index",
        table="reconcile_recovery_phase",
        columns=(
            "phase_id", "incident_id", "started_at", "completed_at",
            "status", "pending_snapshot_count", "reconciled_count",
            "conflict_count", "verified_count", "last_processed_revision",
            "batch_cursor", "conflict_details", "failure_reason",
        ),
        indexes=("reconcile_recovery_incident_idx",),
    ),
    TableContract(
        schema="gptbridge_index",
        table="recovery_generation",
        columns=(
            "generation_id", "generation_number", "incident_id",
            "generation_type", "previous_generation", "started_at",
            "ended_at", "description",
        ),
        indexes=("recovery_gen_number_idx",),
    ),
    TableContract(
        schema="gptbridge_index",
        table="recovery_barrier",
        columns=(
            "barrier_id", "incident_id", "barrier_type", "raised_at",
            "raised_by", "reason", "critical_reconcile_complete",
            "authority_conflicts_resolved", "integrity_pass",
            "barrier_active", "released_at", "released_by", "release_reason",
        ),
        indexes=("recovery_barrier_active_idx",),
    ),
    TableContract(
        schema="gptbridge_index",
        table="transport_recovery",
        columns=(
            "recovery_id", "incident_id", "request_id", "idempotency_key",
            "operation_id", "resource_revision", "commit_state",
            "detected_at", "resolved_at", "resolved_state",
            "resolution_method", "resolution_notes",
        ),
        indexes=("transport_recovery_idempotency_idx", "transport_recovery_unknown_idx"),
    ),
    TableContract(
        schema="gptbridge_index",
        table="unknown_commit_resolution",
        columns=(
            "resolution_id", "transport_recovery_id", "idempotency_key",
            "operation_id", "resource_revision", "lookup_method",
            "lookup_result", "found_committed", "resolved_state",
            "resolved_at", "resolved_by", "notes",
        ),
        indexes=("unknown_commit_res_key_idx",),
    ),
    TableContract(
        schema="gptbridge_index",
        table="lease_recovery",
        columns=(
            "lease_recovery_id", "incident_id", "request_id",
            "original_worker", "original_claimed_at", "lease_until",
            "worker_generation", "lease_status", "checked_at",
            "reclaimed_at", "reclaimed_by", "attempt_history",
        ),
        indexes=("lease_recovery_status_idx",),
    ),
    TableContract(
        schema="gptbridge_index",
        table="recovery_priority",
        columns=(
            "priority_id", "priority_class", "priority_level",
            "description", "max_parallel", "timeout_seconds", "created_at",
        ),
        indexes=(),
    ),
    TableContract(
        schema="gptbridge_index",
        table="backup_restore_orchestration",
        columns=(
            "orchestration_id", "incident_id", "backup_id", "backup_hash",
            "hash_verified", "temp_instance_name", "status",
            "started_at", "completed_at", "schema_verified",
            "release_verified", "rls_verified", "audit_verified",
            "integrity_verified", "promoted", "post_backup_reconciled",
            "failure_reason",
        ),
        indexes=("backup_restore_status_idx",),
    ),
    TableContract(
        schema="gptbridge_index",
        table="pitr_boundary",
        columns=(
            "pitr_id", "incident_id", "restore_target",
            "database_generation", "audit_head_hash",
            "transport_cutoff", "reconcile_cutoff",
            "pg_state_at_target",
            "vector_state_ahead", "cross_engine_reconcile_done",
            "cross_engine_reconcile_started_at",
            "cross_engine_reconcile_completed_at",
            "started_at", "notes",
        ),
        indexes=("pitr_boundary_incident_idx",),
    ),
    TableContract(
        schema="gptbridge_index",
        table="recovery_retry_policy",
        columns=(
            "policy_id", "plan_id", "step_name", "max_attempts",
            "timeout_seconds", "backoff_strategy",
            "initial_delay_seconds", "max_delay_seconds",
            "escalation_action", "created_at",
        ),
        indexes=("recovery_retry_plan_idx",),
    ),
    TableContract(
        schema="gptbridge_index",
        table="recovery_checkpoint",
        columns=(
            "checkpoint_id", "recovery_run_id", "incident_id",
            "current_phase", "last_completed_step",
            "last_processed_revision", "batch_cursor", "generation",
            "total_processed", "total_failed", "saved_at",
            "resumed_at", "resumed_count", "status",
        ),
        indexes=("recovery_checkpoint_run_idx", "recovery_checkpoint_active_idx"),
    ),
    TableContract(
        schema="gptbridge_index",
        table="recovery_idempotency",
        columns=(
            "idempotency_id", "recovery_run_id", "operation_key",
            "operation_type", "completed", "completed_at",
            "result", "attempts", "created_at",
        ),
        indexes=("recovery_idempotency_run_idx",),
    ),
    TableContract(
        schema="gptbridge_index",
        table="recovery_safety_fence",
        columns=(
            "fence_id", "forbidden_action", "description",
            "requires_authority", "blocked_count", "last_blocked_at",
            "created_at",
        ),
        indexes=(),
    ),
    TableContract(
        schema="gptbridge_index",
        table="chaos_drill",
        columns=(
            "drill_id", "scenario_code", "scenario_name", "description",
            "plan_id", "started_at", "completed_at", "status",
            "no_authority_inversion", "no_duplicate_write",
            "no_lost_commit", "no_silent_conflict",
            "no_uncontrolled_retry", "overall_passed",
            "failure_reason", "drill_log",
        ),
        indexes=("chaos_drill_status_idx", "chaos_drill_scenario_idx"),
    ),
    TableContract(
        schema="gptbridge_index",
        table="recovery_certification",
        columns=(
            "certification_id", "plan_id", "plan_version",
            "test_scenario", "database_release_id",
            "starting_generation", "ending_generation",
            "rpo_result", "rto_result", "rpo_seconds", "rto_seconds",
            "integrity_result", "reconcile_result", "audit_result",
            "certification_status", "certified_at", "certified_by",
            "expires_at", "notes", "created_at",
        ),
        indexes=("recovery_cert_plan_idx", "recovery_cert_status_idx"),
    ),
    # Phase K: data layer contract
    TableContract(
        schema="gptbridge_index",
        table="data_layer_contract",
        columns=(
            "contract_id", "contract_version", "database_release_id",
            "postgresql_schema_version",
            "vector_contract_version", "security_generation",
            "data_generation", "required_capabilities",
            "optional_capabilities", "startup_order", "shutdown_order",
            "degradation_policy", "recovery_policy", "status",
            "created_at", "activated_at", "updated_at",
        ),
        indexes=("data_layer_contract_status_idx", "data_layer_contract_version_idx"),
    ),
    TableContract(
        schema="gptbridge_index",
        table="dependency_classification",
        columns=(
            "classification_id", "component_name", "dependency_type",
            "component_category", "failure_effect", "criticality",
            "fallback_component", "fallback_boundary", "description",
            "created_at", "updated_at",
        ),
        indexes=("dep_class_type_idx", "dep_class_category_idx"),
    ),
    TableContract(
        schema="gptbridge_index",
        table="startup_phase",
        columns=(
            "phase_id", "phase_number", "phase_name", "description",
            "required_components", "write_enabled", "can_accept_requests",
            "created_at",
        ),
        indexes=(),
    ),
    TableContract(
        schema="gptbridge_index",
        table="startup_phase_gate",
        columns=(
            "gate_id", "phase_number", "gate_name", "gate_type",
            "check_expression", "required_for_write",
            "required_for_requests", "passed", "checked_at",
            "failure_reason", "created_at",
        ),
        indexes=("startup_gate_phase_idx", "startup_gate_write_idx"),
    ),
    TableContract(
        schema="gptbridge_index",
        table="schema_readiness",
        columns=(
            "readiness_id", "schema_name", "ready", "checked_at",
            "schema_version", "migration_head", "rls_enabled",
            "force_rls", "required_roles_present",
            "public_grants_revoked", "security_generation",
            "failure_reason", "updated_at",
        ),
        indexes=("schema_readiness_ready_idx",),
    ),
    TableContract(
        schema="gptbridge_index",
        table="rag_readiness_gate",
        columns=(
            "gate_id", "checked_at", "pg_rag_metadata_ready",
            "vector_ready", "metadata_authority_wired",
            "collection_contract_valid", "rag_ready", "failure_reason",
        ),
        indexes=("rag_gate_ready_idx",),
    ),
    TableContract(
        schema="gptbridge_index",
        table="shutdown_phase",
        columns=(
            "phase_id", "phase_number", "phase_name", "description",
            "actions", "timeout_seconds", "created_at",
        ),
        indexes=(),
    ),
    TableContract(
        schema="gptbridge_index",
        table="shutdown_audit",
        columns=(
            "shutdown_id", "started_at", "completed_at",
            "shutdown_status", "drain_result", "pending_operations",
            "pending_transport", "reconcile_pending",
            "database_generation", "security_generation",
            "active_leases_released", "active_leases_expired",
            "vector_cursor_saved",
            "audit_flushed", "notes",
        ),
        indexes=("shutdown_audit_status_idx",),
    ),
    TableContract(
        schema="gptbridge_index",
        table="unclean_shutdown_detection",
        columns=(
            "detection_id", "detected_at", "last_shutdown_id",
            "was_graceful", "extra_recovery_steps", "steps_completed",
            "all_steps_done", "completed_at",
        ),
        indexes=("unclean_detect_at_idx",),
    ),
    TableContract(
        schema="gptbridge_index",
        table="cache_invalidation_policy",
        columns=(
            "policy_id", "cache_name", "check_generation_compatible",
            "check_revision_compatible", "check_ttl_valid",
            "ttl_seconds", "on_mismatch", "created_at",
        ),
        indexes=("cache_inval_name_idx",),
    ),
    TableContract(
        schema="gptbridge_index",
        table="data_layer_dependency_graph",
        columns=(
            "edge_id", "from_component", "to_component",
            "edge_type", "boundary", "description", "created_at",
        ),
        indexes=("dep_graph_from_idx", "dep_graph_to_idx"),
    ),
    TableContract(
        schema="gptbridge_index",
        table="integration_rule",
        columns=(
            "rule_id", "rule_number", "rule_text", "rule_category",
            "enforced_by", "violation_effect", "active", "created_at",
        ),
        indexes=("integration_rule_number_idx",),
    ),
)
