"""Chinese Semantic Engine — lexicon data (split from chinese_semantic_engine, A185).

Static vocabularies and marker tables for deterministic Traditional-Chinese
semantic analysis.  Pure data module: no logic, no I/O.
"""

from __future__ import annotations

import re
from typing import Mapping

SCHEMA = "star-chinese-semantics/v1"

UNDERSTANDING_FEATURES: tuple[str, ...] = (
    "original-traditional-chinese-preservation",
    "taiwan-chinese-synonym-normalization",
    "colloquial-ellipsis-typo-and-mixed-language-input",
    "active-verb-and-operation-object-detection",
    "parameter-and-specific-constraint-extraction",
    "conversation-context-completion",
    "destructive-ambiguity-safety-confirmation",
    "multi-intent-planning",
    "question-type-detection",
    "negation-detection",
    "constraint-extraction",
    "requested-output-detection",
    "keyword-extraction",
    "date-percentage-money-url-email-entities",
    "mixed-language-detection",
)

#: Mainland-Chinese terms → Taiwan-Chinese canonical terms.
TAIWAN_SYNONYMS: Mapping[str, str] = {
    "軟件": "軟體",
    "硬件": "硬體",
    "網絡": "網路",
    "互联网": "網際網路",
    "信息": "資訊",
    "視頻": "影片",
    "音頻": "音訊",
    "硬盤": "硬碟",
    "內存": "記憶體",
    "緩存": "快取",
    "激光": "雷射",
    "打印": "列印",
    "打印機": "印表機",
    "默認": "預設",
    "配置文件": "設定檔",
    "鼠標": "滑鼠",
    "屏幕": "螢幕",
    "顯示屏": "顯示器",
    "服務器": "伺服器",
    "移動電話": "行動電話",
    "出租車": "計程車",
    "自行車": "腳踏車",
    "質量": "品質",
    "項目": "專案",
    "文檔": "文件",
    "菜單": "選單",
    "芯片": "晶片",
    "智能": "智慧",
    "算法": "演算法",
    "數據庫": "資料庫",
    "數據": "資料",
    "日誌": "紀錄",
    "登錄": "登入",
    "退出": "登出",
    "卸載": "解除安裝",
    "加載": "載入",
    "保存": "儲存",
    "剪切": "剪下",
    "粘貼": "貼上",
    "刷新": "重新整理",
    "字節": "位元組",
    "代碼": "程式碼",
}

#: Colloquial spellings, common typos and mixed-script repairs.  Only
#: unambiguous multi-character forms are listed; single characters that also
#: occur inside normal words (醬油, 粉絲, 偶像) are deliberately excluded.
COLLOQUIAL_REPAIRS: Mapping[str, str] = {
    "甚麼": "什麼",
    "那裏": "那裡",
    "裏面": "裡面",
    "臺灣": "台灣",
    "醬子": "這樣子",
    "口以": "可以",
    "粗乃": "出來",
    "ㄉ": "的",
    "ㄌ": "了",
    "ㄅ": "不",
    "ㄏ": "很",
    "ㄇ": "嗎",
}

INTENT_LEXICON: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("coding", ("程式", "程式碼", "代碼", "函式", "函數", "腳本", "重構", "編譯", "測試", "python", "javascript", "typescript", "修 bug", "修復程式")),
    ("search", ("搜尋", "查詢", "找一下", "幫我找", "上網", "檢索", "查資料", "search")),
    ("analysis", ("分析", "比較", "評估", "判斷", "推論", "統計", "趨勢", "風險")),
    ("status", ("狀態", "健康", "目前", "現在", "進度", "模型", "版本", "設定", "組態")),
    ("reading", ("閱讀", "讀取", "摘要這份", "這份文件", "這篇文章", "文件內容")),
    ("visual", ("圖片", "照片", "影像", "影片", "截圖", "圖表", "ocr")),
    ("data_organization", ("整理", "歸類", "分類", "排序", "清單", "表格", "資料整理")),
    ("calculation", ("計算", "算一下", "加總", "平均", "百分比", "公式")),
    ("investment", ("股票", "台股", "美股", "投資", "持股", "股利", "行情", "股價", "基金")),
    ("memory", ("記憶", "記住", "回想", "之前說過", "上次提到")),
    ("training", ("訓練", "微調", "學習", "模型訓練", "資料集")),
    ("repair", ("修復", "維修", "排除", "故障", "錯誤", "異常", "壞掉")),
    ("self_upgrade", ("自我升級", "自我更新", "升級自己", "更新模型")),
    ("command_execution", ("執行", "跑一下", "啟動", "停止", "關閉", "開啟", "部署")),
    ("conversation", ("你好", "您好", "哈囉", "嗨", "聊聊", "謝謝", "請問你是")),
)

#: Destructive actions that require unambiguous intent.
DESTRUCTIVE_ACTIONS: frozenset[str] = frozenset(
    {"delete", "remove", "overwrite", "format", "reset", "terminate", "drop"}
)

#: Governance surfaces that a request may never mutate.
PROHIBITED_SURFACES: tuple[str, ...] = (
    "法典",
    "治理規則",
    "權限設定",
    "governance_rule",
    "permission_directory",
    "法典資料庫",
)

ACTION_LEXICON: tuple[tuple[str, str], ...] = (
    ("建立", "create"),
    ("新增", "create"),
    ("產生", "generate"),
    ("生成", "generate"),
    ("撰寫", "generate"),
    ("修改", "modify"),
    ("調整", "modify"),
    ("更新", "update"),
    ("刪除", "delete"),
    ("移除", "remove"),
    ("清空", "delete"),
    ("覆蓋", "overwrite"),
    ("格式化", "format"),
    ("重設", "reset"),
    ("重置", "reset"),
    ("移動", "move"),
    ("搬移", "move"),
    ("複製", "copy"),
    ("重新命名", "rename"),
    ("改名", "rename"),
    ("執行", "execute"),
    ("啟動", "execute"),
    ("停止", "stop"),
    ("終止", "terminate"),
    ("開啟", "open"),
    ("關閉", "close"),
    ("查詢", "query"),
    ("搜尋", "search"),
    ("讀取", "read"),
    ("寫入", "write"),
    ("匯出", "export"),
    ("匯入", "import"),
    ("備份", "backup"),
    ("還原", "restore"),
    ("排程", "schedule"),
    ("分析", "analyze"),
    ("整理", "organize"),
    ("摘要", "summarize"),
    ("翻譯", "translate"),
)

OBJECT_LEXICON: tuple[tuple[str, str], ...] = (
    ("資料庫", "database"),
    ("資料表", "database-table"),
    ("檔案", "file"),
    ("文件", "file"),
    ("資料夾", "folder"),
    ("目錄", "folder"),
    ("程式碼", "code"),
    ("程式", "code"),
    ("腳本", "script"),
    ("報告", "report"),
    ("報表", "report"),
    ("圖表", "chart"),
    ("設定", "settings"),
    ("組態", "settings"),
    ("模型", "model"),
    ("權重", "model-weights"),
    ("記憶", "memory"),
    ("任務", "task"),
    ("工具", "tool"),
    ("網頁", "web-page"),
    ("圖片", "image"),
    ("影片", "video"),
    ("備份", "backup"),
    ("日誌", "log"),
    ("紀錄", "log"),
    ("郵件", "email"),
    ("帳號", "account"),
    ("排程", "schedule"),
    ("服務", "service"),
    ("系統", "system"),
)

NEGATION_MARKERS: tuple[str, ...] = (
    "不要",
    "不用",
    "不需要",
    "不必",
    "別",
    "勿",
    "禁止",
    "不可以",
    "不准",
    "不得",
    "無需",
    "毋須",
    "no",
    "don't",
    "do not",
)

QUESTION_MARKERS: tuple[tuple[str, str], ...] = (
    ("嗎", "yes-no"),
    ("呢", "follow-up"),
    ("是否", "yes-no"),
    ("可否", "permission"),
    ("能不能", "capability"),
    ("可不可以", "permission"),
    ("什麼", "what"),
    ("甚麼", "what"),
    ("哪些", "which"),
    ("哪個", "which"),
    ("哪裡", "where"),
    ("何時", "when"),
    ("什麼時候", "when"),
    ("為什麼", "why"),
    ("為何", "why"),
    ("如何", "how"),
    ("怎麼", "how"),
    ("誰", "who"),
    ("多少", "how-many"),
    ("幾個", "how-many"),
)

CONSTRAINT_MARKERS: tuple[str, ...] = (
    "至少",
    "最多",
    "不超過",
    "超過",
    "限定",
    "只能",
    "只可以",
    "必須",
    "一定要",
    "範圍",
    "格式",
    "字數",
    "字以內",
    "分鐘內",
    "小時內",
    "天內",
    "以內",
    "以外",
)

REQUESTED_OUTPUT_MARKERS: tuple[tuple[str, str], ...] = (
    ("表格", "table"),
    ("清單", "list"),
    ("列表", "list"),
    ("摘要", "summary"),
    ("報告", "report"),
    ("json", "json"),
    ("csv", "csv"),
    ("程式碼", "code"),
    ("步驟", "steps"),
    ("建議", "recommendation"),
    ("比較", "comparison"),
    ("分析", "analysis"),
    ("結論", "conclusion"),
)

REFERENCE_MARKERS: tuple[str, ...] = (
    "它",
    "他",
    "她",
    "這個",
    "那個",
    "上述",
    "上面",
    "剛剛",
    "前面",
    "同樣",
    "再",
    "也",
    "那份",
    "這份",
)

MULTI_INTENT_MARKERS: tuple[str, ...] = ("並且", "然後", "以及", "同時", "還有", "接著", "再來", "並")

MARKET_ALIASES: Mapping[str, str] = {
    "台股": "TW",
    "臺股": "TW",
    "美股": "US",
    "日股": "JP",
    "港股": "HK",
    "陸股": "CN",
    "歐股": "EU",
}

_NUMERIC_TOKEN = re.compile(r"\d+(?:\.\d+)*")

STOPWORDS: frozenset[str] = frozenset(
    {
        "的",
        "了",
        "是",
        "在",
        "我",
        "你",
        "他",
        "她",
        "它",
        "我們",
        "你們",
        "他們",
        "這",
        "那",
        "個",
        "請",
        "幫",
        "把",
        "給",
        "跟",
        "和",
        "與",
        "或",
        "就",
        "都",
        "很",
        "也",
        "還",
        "要",
        "有",
        "沒有",
        "可以",
        "一下",
        "嗎",
        "呢",
        "吧",
        "啊",
        "喔",
        "哦",
    }
)
