from __future__ import annotations

from typing import Any, Mapping


class TransformerRuntimeMetadata:
    """Known-model metadata catalog for StarTransformerRuntime."""

    KNOWN_MODEL_METADATA: Mapping[str, Mapping[str, Any]] = {
        "nemotron-3.5-lightning:30b-a3b-q4_K_M": {
            "label": "Nemotron 3.5 Lightning 30B · 任務規劃與分派",
            "family": "Nemotron 3.5 Lightning",
            "parameter_class": "30B-A3B",
            "parameter_count": "32.9B total",
            "quantization": "Q4_K_M",
            "architecture": "nemotron-h-mixture-of-experts-transformer",
            "context_window": 1_048_576,
            "license": "NVIDIA-Open-Model-License",
            "usage_class": "task-planning-allocation-and-automation",
            "residency": "non-resident",
            "evaluation": {"speed": 4, "strength": 5, "reasoning_depth": 5},
        },
        "ornith-1.5:35b": {
            "label": "Ornith 1.5 35B · 高階 Agent 備援",
            "family": "Ornith 1.5",
            "parameter_class": "35B-A3B",
            "parameter_count": "35.5B total",
            "quantization": "Q4_K_M",
            "architecture": "qwen35-mixture-of-experts-transformer",
            "context_window": 262_144,
            "license": "model-specific-license",
            "usage_class": "advanced-agent-and-planning-backup",
            "residency": "non-resident",
            "evaluation": {"speed": 3, "strength": 5, "reasoning_depth": 5},
        },
        "qwen3-coder:30b-a3b-q4_K_M": {
            "label": "Qwen3-Coder 30B · Coding 與執行備援",
            "family": "Qwen3 Coder",
            "parameter_class": "30B-A3B",
            "parameter_count": "30.5B total",
            "quantization": "Q4_K_M",
            "architecture": "qwen3-mixture-of-experts-transformer",
            "context_window": 262_144,
            "license": "Apache-2.0",
            "usage_class": "coding-and-command-execution-backup",
            "residency": "non-resident",
            "evaluation": {"speed": 3, "strength": 5, "reasoning_depth": 5},
        },
        "deepcoder:14b": {
            "label": "DeepCoder 14B · Code Review",
            "family": "DeepCoder",
            "parameter_class": "14B",
            "parameter_count": "14.8B",
            "quantization": "Q4_K_M",
            "architecture": "qwen2-dense-decoder-transformer",
            "context_window": 131_072,
            "license": "model-specific-license",
            "usage_class": "code-review-debugging-and-verification",
            "residency": "non-resident",
            "evaluation": {"speed": 3, "strength": 4, "reasoning_depth": 5},
        },
        "granite-code:3b": {
            "label": "Granite Code 3B · 輕量 Coding",
            "family": "Granite Code",
            "parameter_class": "3B",
            "parameter_count": "3.5B",
            "quantization": "Q4_0",
            "architecture": "dense-decoder-transformer",
            "context_window": 128_000,
            "license": "Apache-2.0",
            "usage_class": "fast-lightweight-coding",
            "residency": "non-resident",
            "evaluation": {"speed": 5, "strength": 3, "reasoning_depth": 2},
        },
        "deepseek-r1:14b": {
            "label": "DeepSeek-R1 14B · 深度推理與複核",
            "family": "DeepSeek-R1",
            "parameter_class": "14B",
            "parameter_count": "14.8B",
            "quantization": "Q4_K_M",
            "architecture": "qwen2-dense-decoder-transformer",
            "context_window": 131_072,
            "license": "MIT",
            "usage_class": "deep-reasoning-and-independent-review",
            "residency": "non-resident",
            "evaluation": {"speed": 3, "strength": 5, "reasoning_depth": 5},
        },
        "ibm/granite4.2:30b-q4_K_M": {
            "label": "Granite 4.2 30B · 企業文件與資料整合",
            "family": "Granite 4.2",
            "parameter_class": "30B",
            "parameter_count": "29.3B",
            "quantization": "Q4_K_M",
            "architecture": "granite-decoder-transformer",
            "context_window": 131_072,
            "license": "Apache-2.0",
            "usage_class": "enterprise-document-data-and-integration-backup",
            "residency": "non-resident",
            "evaluation": {"speed": 3, "strength": 4, "reasoning_depth": 4},
        },
        "mistral-small:24b": {
            "label": "Mistral Small 24B · RAG 整合",
            "family": "Mistral Small",
            "parameter_class": "24B",
            "parameter_count": "23.6B",
            "quantization": "Q4_K_M",
            "architecture": "llama-compatible-decoder-transformer",
            "context_window": 32_768,
            "license": "Apache-2.0",
            "usage_class": "rag-grounded-synthesis",
            "residency": "non-resident",
            "evaluation": {"speed": 3, "strength": 4, "reasoning_depth": 4},
        },
        "gemma4:26b-a4b-it-qat": {
            "label": "Gemma 4 26B · 長文與多模態理解",
            "family": "Gemma 4",
            "parameter_class": "26B-A4B",
            "parameter_count": "25.2B",
            "quantization": "QAT-4bit",
            "architecture": "dense-hybrid-attention-decoder-transformer",
            "context_window": 262_144,
            "license": "Apache-2.0",
            "usage_class": "long-form-and-multimodal-understanding",
            "residency": "non-resident",
            "evaluation": {"speed": 2, "strength": 5, "reasoning_depth": 4},
        },
        "gemma4:12b-it-qat": {
            "label": "Gemma 4 12B · 文件閱讀與摘要",
            "family": "Gemma 4",
            "parameter_class": "12B",
            "parameter_count": "11.9B",
            "quantization": "QAT-4bit",
            "architecture": "dense-hybrid-attention-decoder-transformer",
            "context_window": 262_144,
            "license": "Apache-2.0",
            "usage_class": "document-reading-and-summarization",
            "residency": "non-resident",
            "evaluation": {"speed": 3, "strength": 4, "reasoning_depth": 4},
        },
        "qwen3-vl:8b-thinking": {
            "label": "Qwen3-VL 8B Thinking · 視覺 RAG",
            "family": "Qwen3 VL",
            "parameter_class": "8B",
            "parameter_count": "8.8B",
            "quantization": "Q4_K_M",
            "architecture": "multimodal-vision-language-transformer",
            "context_window": 262_144,
            "license": "Apache-2.0",
            "usage_class": "visual-rag-only",
            "residency": "non-resident",
            "evaluation": {"speed": 3, "strength": 4, "reasoning_depth": 5},
        },
        "glm4:9b": {
            "label": "GLM-4 9B · 中文對話備援",
            "family": "GLM-4",
            "parameter_class": "9B",
            "parameter_count": "9.4B",
            "quantization": "Q4_0",
            "architecture": "chatglm-decoder-transformer",
            "context_window": 131_072,
            "license": "GLM-4-License",
            "usage_class": "traditional-chinese-conversation-and-analysis",
            "residency": "non-resident",
            "evaluation": {"speed": 4, "strength": 4, "reasoning_depth": 3},
        },
        "rnj-1:8b-instruct-q4_K_M": {
            "label": "RNJ-1 8B · 通用回覆備援",
            "family": "RNJ-1",
            "parameter_class": "8B",
            "parameter_count": "8.3B",
            "quantization": "Q4_K_M",
            "architecture": "gemma3-decoder-transformer",
            "context_window": 32_768,
            "license": "Apache-2.0",
            "usage_class": "general-response-and-tool-backup",
            "residency": "non-resident",
            "evaluation": {"speed": 4, "strength": 4, "reasoning_depth": 3},
        },
        "nemotron-3-nano:4b-q8_0": {
            "label": "Nemotron 3 Nano 4B · Q8 · 輕量工具",
            "family": "Nemotron 3 Nano",
            "parameter_class": "4B",
            "parameter_count": "4.0B",
            "quantization": "Q8_0",
            "architecture": "nemotron-h-hybrid-transformer",
            "context_window": 262_144,
            "license": "NVIDIA-Open-Model-License",
            "usage_class": "lightweight-tool-reasoning",
            "residency": "non-resident",
            "daily_group": "lightweight",
            "evaluation": {"speed": 5, "strength": 3, "reasoning_depth": 4},
        },
        "openbmb/minicpm-v4.6:q8_0": {
            "label": "MiniCPM-V 4.6 · Q8_0 · 視覺辨識專員",
            "family": "MiniCPM-V 4.6",
            "parameter_class": "multimodal-service-model",
            "parameter_count": "runtime-reported",
            "quantization": "Q8_0",
            "architecture": "multimodal-vision-language-transformer",
            "context_window": 32_768,
            "license": "model-specific-license",
            "usage_class": "automatic-file-management-visual-recognition-only",
            "residency": "non-resident",
            "evaluation": {"speed": 3, "strength": 4, "reasoning_depth": 3},
            "allowed_intents": ["visual"],
        },
        "nemotron-3-nano:4b": {
            "label": "Nemotron 3 Nano 4B · Q4",
            "family": "Nemotron 3 Nano",
            "parameter_class": "4B",
            "parameter_count": "4.0B",
            "quantization": "Q4_K_M",
            "architecture": "nemotron-h-hybrid-transformer",
            "context_window": 262_144,
            "license": "NVIDIA-Open-Model-License",
            "usage_class": "lightweight-tool-reasoning",
            "residency": "non-resident",
            "daily_group": "lightweight",
            "evaluation": {"speed": 5, "strength": 3, "reasoning_depth": 4},
        },
        "qwen2.5-coder:7b": {
            "label": "Qwen2.5 Coder 7B · Q4",
            "family": "Qwen2.5 Coder",
            "parameter_class": "7B",
            "parameter_count": "7.6B",
            "quantization": "Q4_K_M",
            "architecture": "qwen2-dense-decoder-only-transformer",
            "context_window": 32_768,
            "license": "Apache-2.0",
            "usage_class": "fast-coding-and-command-execution",
            "residency": "non-resident",
            "evaluation": {"speed": 4, "strength": 4, "reasoning_depth": 3},
        },
        "qwen3.8:27b-q4_K_M": {
            "label": "Qwen3.8 27B · 作業總指揮",
            "family": "Qwen3.8",
            "parameter_class": "27B",
            "parameter_count": "27.3B",
            "quantization": "Q4_K_M",
            "architecture": "qwen35-multimodal-decoder-only-transformer",
            "context_window": 262_144,
            "license": "Apache-2.0",
            "usage_class": "task-commander-chinese-understanding-integration-acceptance",
            "residency": "non-resident",
            "evaluation": {"speed": 1, "strength": 5, "reasoning_depth": 5},
        },
        "qwen3.6:35b-a3b-coding": {
            "label": "Qwen3.6 35B-A3B Coding · 主程式工程師",
            "family": "Qwen3.6 Coding",
            "parameter_class": "35B-A3B",
            "parameter_count": "35B total / 3B active",
            "quantization": "Q4_K_M",
            "architecture": "hybrid-attention-mixture-of-experts-transformer",
            "context_window": 262_144,
            "license": "Apache-2.0",
            "usage_class": "repository-engineering-test-repair-and-command-execution",
            "residency": "non-resident",
            "evaluation": {"speed": 3, "strength": 5, "reasoning_depth": 5},
        },
        "gpt-oss:20b": {
            "label": "GPT-OSS 20B · MXFP4",
            "family": "GPT-OSS",
            "parameter_class": "20B",
            "parameter_count": "20.9B total / 3.6B active",
            "quantization": "MXFP4",
            "architecture": "mixture-of-experts-decoder-transformer",
            "context_window": 131_072,
            "license": "Apache-2.0",
            "usage_class": "integration-coordinator",
            "residency": "non-resident",
            "evaluation": {"speed": 3, "strength": 5, "reasoning_depth": 5},
        },
        "qwen3:30b-a3b-instruct-2507-q4_K_M": {
            "label": "Qwen3 30B-A3B Instruct 2507 · Q4",
            "family": "Qwen3",
            "parameter_class": "30B-A3B",
            "parameter_count": "30.5B total / 3.3B active",
            "quantization": "Q4_K_M",
            "architecture": "mixture-of-experts-decoder-transformer",
            "context_window": 262_144,
            "license": "Apache-2.0",
            "usage_class": "complex",
            "residency": "non-resident",
            "evaluation": {"speed": 3, "strength": 5, "reasoning_depth": 5},
        },
        "deepseek-r1:8b-0528-qwen3-q4_K_M": {
            "label": "DeepSeek-R1 0528 Qwen3 8B · Q4",
            "family": "DeepSeek-R1-0528-Qwen3",
            "parameter_class": "8B",
            "parameter_count": "8.19B",
            "quantization": "Q4_K_M",
            "architecture": "qwen3-dense-decoder-transformer",
            "context_window": 131_072,
            "license": "MIT",
            "usage_class": "medium-reasoning",
            "residency": "non-resident",
            "evaluation": {"speed": 4, "strength": 4, "reasoning_depth": 5},
        },
        "qwen3.5:9b-q4_K_M": {
            "label": "Qwen3.5 9B · Q4",
            "family": "Qwen3.5",
            "parameter_class": "9B",
            "parameter_count": "9.65B",
            "quantization": "Q4_K_M",
            "architecture": "hybrid-attention-multimodal-decoder-transformer",
            "context_window": 262_144,
            "license": "Apache-2.0",
            "usage_class": "search-and-tool-coordinator",
            "residency": "resident",
            "evaluation": {"speed": 4, "strength": 4, "reasoning_depth": 4},
        },
        "gemma4:e2b-it-qat": {
            "label": "Gemma 4 E2B · QAT",
            "family": "Gemma 4",
            "parameter_class": "E2B",
            "parameter_count": "2.3B effective / 5.1B total",
            "quantization": "QAT-4bit",
            "architecture": "dense-hybrid-attention-decoder-transformer",
            "context_window": 131_072,
            "license": "Apache-2.0",
            "usage_class": "fast-intake-and-daily",
            "residency": "non-resident",
            "daily_group": "fast",
            "evaluation": {"speed": 5, "strength": 3, "reasoning_depth": 3},
        },
        "llama3.1:8b-instruct-q4_K_M": {
            "label": "Llama 3.1 8B（實際 8.03B）",
            "family": "Llama 3.1",
            "parameter_class": "8B",
            "parameter_count": "8.03B",
            "quantization": "Q4_K_M",
            "architecture": "dense-decoder-only-transformer",
            "license": "Llama-3.1-Community-License",
            "usage_class": "lightweight-manual-model",
            "residency": "non-resident",
            "daily_group": "",
            "evaluation": {"speed": 4, "strength": 4, "reasoning_depth": 5},
        },
    }
