"""Pure domain contracts — 星澄 AI 投資管理與自動操盤系統."""

from .contract import (
    DOMAIN_AI_ANALYSIS,
    DOMAIN_ASSET_MGMT,
    DOMAIN_AUTO_TRADING,
    DOMAIN_FUND,
    DOMAIN_IDS,
    DOMAIN_TW_STOCK,
    DOMAIN_US_STOCK,
    MARKET_DOMAIN,
    TRADING_APP_VERSION,
    TRADING_SCHEMA_VERSION,
)

__all__ = (
    "DOMAIN_AI_ANALYSIS",
    "DOMAIN_ASSET_MGMT",
    "DOMAIN_AUTO_TRADING",
    "DOMAIN_FUND",
    "DOMAIN_IDS",
    "DOMAIN_TW_STOCK",
    "DOMAIN_US_STOCK",
    "MARKET_DOMAIN",
    "TRADING_APP_VERSION",
    "TRADING_SCHEMA_VERSION",
)
