"""Performance Baseline V1 — Python Hotspot & Native Acceleration Benchmark.

Reproducible profile baseline for GPTBridge's main Python execution paths.
Records wall/cpu time, p50/p95/p99, call count, peak memory, allocation,
and hottest callables.  Classifies hotspots and produces versioned baseline
evidence for the existing Native Promotion Gate (A357/A358).

Codex basis:
    A211 — canonical-six-language-role-map (Python=system-control+semantic/
           business logic; C++=profile-proven implementation/performance core).
    A219 — python-api-native-unavailability-fallback (Python fallback always).
    A221 — canonical-native-physical-tree (parser.cpp/vector.cpp/transformer.cpp).
    A357 — native-promotion-gate (PASS/WARN/FAIL based on profile evidence).
    A358 — native-promotion-budget-benchmark-evidence-and-lifecycle
           (end-to-end cost, copy metrics, machine profile, comparability).

Import contract: this package ``__init__`` must stay import-cheap.  The
runtime hot path only needs ``process_metrics`` / ``thread_budget``; the
benchmark and analysis suites below are developer tooling.  Every public
name therefore resolves lazily (PEP 562) so ``import
shared_layer.performance`` never pays for suites nobody called.
"""

from __future__ import annotations

import importlib
from typing import Any

_LAZY_ATTRS: dict[str, str] = {
    # profiler
    "ProfileResult": ".profiler",
    "ProfileSampler": ".profiler",
    "profile_callable": ".profiler",
    "profile_block": ".profiler",
    # baseline
    "BaselineRecord": ".baseline",
    "BaselineStore": ".baseline",
    "MachineProfile": ".baseline",
    "capture_machine_profile": ".baseline",
    # classifier
    "HotspotClassification": ".classifier",
    "classify_hotspot": ".classifier",
    "BOTTLENECK_CLASSES": ".classifier",
    # benchmark
    "BenchmarkConfig": ".benchmark",
    "BenchmarkResult": ".benchmark",
    "BenchmarkSuite": ".benchmark",
    "SizeClass": ".benchmark",
    "WarmthClass": ".benchmark",
    # native_candidate
    "NativeCandidate": ".native_candidate",
    "PromotionVerdict": ".native_candidate",
    "classify_candidate": ".native_candidate",
    "to_promotion_verdict": ".native_candidate",
    "KEEP_PYTHON": ".native_candidate",
    "OPTIMIZE_PYTHON": ".native_candidate",
    "EXPERIMENTAL_NATIVE": ".native_candidate",
    "NATIVE_CANDIDATE": ".native_candidate",
    # regression
    "RegressionEvidence": ".regression",
    "compare_baselines": ".regression",
    "detect_regression": ".regression",
    # budgets
    "PerformanceBudget": ".budgets",
    "BudgetCheckResult": ".budgets",
    "get_budget": ".budgets",
    "list_budgets": ".budgets",
    "check_budget": ".budgets",
    "check_all_budgets": ".budgets",
    # regression_benchmarks
    "run_regression_benchmarks": ".regression_benchmarks",
    "write_regression_report": ".regression_benchmarks",
    # native_dispatcher
    "native_available": ".native_dispatcher",
    "should_dispatch": ".native_dispatcher",
    "get_threshold": ".native_dispatcher",
    "DISPATCH_THRESHOLDS": ".native_dispatcher",
    "token_estimate": ".native_dispatcher",
    "batch_token_estimate": ".native_dispatcher",
    "dot": ".native_dispatcher",
    "l2_norm": ".native_dispatcher",
    "cosine_similarity": ".native_dispatcher",
    "matmul": ".native_dispatcher",
    "softmax": ".native_dispatcher",
    "scaled_dot_product_attention": ".native_dispatcher",
    "python_token_estimate": ".native_dispatcher",
    "python_batch_token_estimate": ".native_dispatcher",
    "python_dot": ".native_dispatcher",
    "python_l2_norm": ".native_dispatcher",
    "python_cosine_similarity": ".native_dispatcher",
    "python_matmul": ".native_dispatcher",
    "python_softmax": ".native_dispatcher",
    "python_scaled_dot_product_attention": ".native_dispatcher",
    "native_token_estimate": ".native_dispatcher",
    "native_batch_token_estimate": ".native_dispatcher",
    "native_dot": ".native_dispatcher",
    "native_l2_norm": ".native_dispatcher",
    "native_cosine_similarity": ".native_dispatcher",
    "native_matmul": ".native_dispatcher",
    "native_softmax": ".native_dispatcher",
    "native_scaled_dot_product_attention": ".native_dispatcher",
    # native_core_benchmark
    "run_native_core_benchmark": ".native_core_benchmark",
    "write_native_benchmark_report": ".native_core_benchmark",
    "classify_native_result": ".native_core_benchmark",
    # perf_baseline
    "PERF_BASELINE_VERSION": ".perf_baseline",
    "EnvironmentProfile": ".perf_baseline",
    "capture_environment_profile": ".perf_baseline",
    "WorkloadProfile": ".perf_baseline",
    "FullMetrics": ".perf_baseline",
    "PerformanceBaselineRecord": ".perf_baseline",
    "PerformanceBaselineStore": ".perf_baseline",
    # perf_tiers
    "BenchmarkTier": ".perf_tiers",
    "TierConfig": ".perf_tiers",
    "TIER_CONFIGS": ".perf_tiers",
    "get_tier_config": ".perf_tiers",
    "select_tier_by_env": ".perf_tiers",
    # perf_tolerance
    "MetricTolerance": ".perf_tolerance",
    "ToleranceSet": ".perf_tolerance",
    "ToleranceCheckResult": ".perf_tolerance",
    "compute_tolerance": ".perf_tolerance",
    "compute_tolerance_set": ".perf_tolerance",
    "check_tolerance": ".perf_tolerance",
    "check_all_tolerances": ".perf_tolerance",
    "LOWER_IS_BETTER": ".perf_tolerance",
    "HIGHER_IS_BETTER": ".perf_tolerance",
    # perf_comparison
    "ComparabilityResult": ".perf_comparison",
    "ComparisonResult": ".perf_comparison",
    "verify_comparability": ".perf_comparison",
    "compare_against_baseline": ".perf_comparison",
    "CRITICAL_ENV_FIELDS": ".perf_comparison",
    "SOFT_ENV_FIELDS": ".perf_comparison",
    # perf_trend
    "MetricTrend": ".perf_trend",
    "RegressionAttribution": ".perf_trend",
    "OperationTrend": ".perf_trend",
    "compute_metric_trend": ".perf_trend",
    "compute_operation_trend": ".perf_trend",
    "attribute_regression": ".perf_trend",
    "METRIC_BOUNDARY_MAP": ".perf_trend",
    # perf_stability
    "StabilityCheck": ".perf_stability",
    "StabilityResult": ".perf_stability",
    "STABILITY_BUDGETS": ".perf_stability",
    "check_stability_budgets": ".perf_stability",
    "assess_stability": ".perf_stability",
    # perf_regression_control
    "RegressionControlReport": ".perf_regression_control",
    "RegressionController": ".perf_regression_control",
    "write_regression_control_report": ".perf_regression_control",
    # dep_graph
    "DependencyType": ".dep_graph",
    "NodeLanguage": ".dep_graph",
    "DepNode": ".dep_graph",
    "DepEdge": ".dep_graph",
    "DependencyGraph": ".dep_graph",
    "build_python_import_graph": ".dep_graph",
    "build_javascript_package_graph": ".dep_graph",
    "build_cc_include_graph": ".dep_graph",
    "build_csharp_project_graph": ".dep_graph",
    "build_sql_migration_graph": ".dep_graph",
    "build_cross_language_build_graph": ".dep_graph",
    "build_all_dependency_graphs": ".dep_graph",
    # dep_classifier
    "DependencyClass": ".dep_classifier",
    "ClassificationEvidence": ".dep_classifier",
    "classify_dependency": ".dep_classifier",
    "classify_all_dependencies": ".dep_classifier",
    "get_remove_candidates": ".dep_classifier",
    "get_optional_without_evidence": ".dep_classifier",
    # dep_version_registry
    "REGISTRY_VERSION": ".dep_version_registry",
    "ApprovedDependency": ".dep_version_registry",
    "DependencyVersionRegistry": ".dep_version_registry",
    "compute_source_hash": ".dep_version_registry",
    "seed_default_registry": ".dep_version_registry",
    # build_baseline
    "BUILD_BASELINE_VERSION": ".build_baseline",
    "BuildStepResult": ".build_baseline",
    "BuildBaselineRecord": ".build_baseline",
    "BuildBaselineStore": ".build_baseline",
    "run_python_import_baseline": ".build_baseline",
    "run_cc_compile_baseline": ".build_baseline",
    "run_sql_migration_validation_baseline": ".build_baseline",
    "run_full_build_baseline": ".build_baseline",
    # build_impact
    "ChangeType": ".build_impact",
    "BuildImpactResult": ".build_impact",
    "classify_change": ".build_impact",
    "analyze_build_impact": ".build_impact",
    "get_minimal_rebuild_set": ".build_impact",
    # dep_consolidator
    "ConsolidationFinding": ".dep_consolidator",
    "ConsolidationReport": ".dep_consolidator",
    "find_unused_dependencies": ".dep_consolidator",
    "find_duplicate_versions": ".dep_consolidator",
    "find_transitive_pollution": ".dep_consolidator",
    "find_duplicate_build_entries": ".dep_consolidator",
    "find_lazy_load_candidates": ".dep_consolidator",
    "run_consolidation_analysis": ".dep_consolidator",
}


def __getattr__(name: str) -> Any:
    """Lazily resolve a public performance-suite name (PEP 562)."""
    module_name = _LAZY_ATTRS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = importlib.import_module(module_name, __name__)
    value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted([*globals(), *_LAZY_ATTRS])


__all__ = [
    "ProfileResult",
    "ProfileSampler",
    "profile_callable",
    "profile_block",
    "BaselineRecord",
    "BaselineStore",
    "MachineProfile",
    "capture_machine_profile",
    "HotspotClassification",
    "classify_hotspot",
    "BOTTLENECK_CLASSES",
    "BenchmarkConfig",
    "BenchmarkResult",
    "BenchmarkSuite",
    "SizeClass",
    "WarmthClass",
    "NativeCandidate",
    "PromotionVerdict",
    "classify_candidate",
    "to_promotion_verdict",
    "KEEP_PYTHON",
    "OPTIMIZE_PYTHON",
    "EXPERIMENTAL_NATIVE",
    "NATIVE_CANDIDATE",
    "RegressionEvidence",
    "compare_baselines",
    "detect_regression",
    "PerformanceBudget",
    "BudgetCheckResult",
    "get_budget",
    "list_budgets",
    "check_budget",
    "check_all_budgets",
    "run_regression_benchmarks",
    "write_regression_report",
    "native_available",
    "should_dispatch",
    "get_threshold",
    "DISPATCH_THRESHOLDS",
    "token_estimate",
    "batch_token_estimate",
    "dot",
    "l2_norm",
    "cosine_similarity",
    "matmul",
    "softmax",
    "scaled_dot_product_attention",
    "python_token_estimate",
    "python_batch_token_estimate",
    "python_dot",
    "python_l2_norm",
    "python_cosine_similarity",
    "python_matmul",
    "python_softmax",
    "python_scaled_dot_product_attention",
    "native_token_estimate",
    "native_batch_token_estimate",
    "native_dot",
    "native_l2_norm",
    "native_cosine_similarity",
    "native_matmul",
    "native_softmax",
    "native_scaled_dot_product_attention",
    "run_native_core_benchmark",
    "write_native_benchmark_report",
    "classify_native_result",
    # Performance Budget & Regression Control V1
    "PERF_BASELINE_VERSION",
    "EnvironmentProfile",
    "capture_environment_profile",
    "WorkloadProfile",
    "FullMetrics",
    "PerformanceBaselineRecord",
    "PerformanceBaselineStore",
    "BenchmarkTier",
    "TierConfig",
    "TIER_CONFIGS",
    "get_tier_config",
    "select_tier_by_env",
    "MetricTolerance",
    "ToleranceSet",
    "ToleranceCheckResult",
    "compute_tolerance",
    "compute_tolerance_set",
    "check_tolerance",
    "check_all_tolerances",
    "LOWER_IS_BETTER",
    "HIGHER_IS_BETTER",
    "ComparabilityResult",
    "ComparisonResult",
    "verify_comparability",
    "compare_against_baseline",
    "CRITICAL_ENV_FIELDS",
    "SOFT_ENV_FIELDS",
    "MetricTrend",
    "RegressionAttribution",
    "OperationTrend",
    "compute_metric_trend",
    "compute_operation_trend",
    "attribute_regression",
    "METRIC_BOUNDARY_MAP",
    "StabilityCheck",
    "StabilityResult",
    "STABILITY_BUDGETS",
    "check_stability_budgets",
    "assess_stability",
    "RegressionControlReport",
    "RegressionController",
    "write_regression_control_report",
    "DependencyType",
    "NodeLanguage",
    "DepNode",
    "DepEdge",
    "DependencyGraph",
    "build_python_import_graph",
    "build_javascript_package_graph",
    "build_cc_include_graph",
    "build_csharp_project_graph",
    "build_sql_migration_graph",
    "build_cross_language_build_graph",
    "build_all_dependency_graphs",
    "DependencyClass",
    "ClassificationEvidence",
    "classify_dependency",
    "classify_all_dependencies",
    "get_remove_candidates",
    "get_optional_without_evidence",
    "REGISTRY_VERSION",
    "ApprovedDependency",
    "DependencyVersionRegistry",
    "compute_source_hash",
    "seed_default_registry",
    "BUILD_BASELINE_VERSION",
    "BuildStepResult",
    "BuildBaselineRecord",
    "BuildBaselineStore",
    "run_python_import_baseline",
    "run_cc_compile_baseline",
    "run_sql_migration_validation_baseline",
    "run_full_build_baseline",
    "ChangeType",
    "BuildImpactResult",
    "classify_change",
    "analyze_build_impact",
    "get_minimal_rebuild_set",
    "ConsolidationFinding",
    "ConsolidationReport",
    "find_unused_dependencies",
    "find_duplicate_versions",
    "find_transitive_pollution",
    "find_duplicate_build_entries",
    "find_lazy_load_candidates",
    "run_consolidation_analysis",
]
